spring:
  datasource:
    url: 'jdbc:postgresql://postgres.maa-org.net/dev'
    username: 'dev-service-user'
    password: 'r9soGiNHem7H4LIM'


logging:
  level:
    org.maa.server.gamedata.mapper: warn