spring:
  datasource:
    url: 'jdbc:postgresql://postgres.data-storage.svc.cluster.local/prod'
    username: 'prod-service-user'
    password: 'hHfIsLNRrwFJKc6Q'


logging:
  level:
    org.maa.server.gamedata.mapper: warn