spring:
  datasource:
    url: 'jdbc:postgresql://postgres.maa-org.net/dev'
    username: 'dev-service-user'
    password: 'r9soGiNHem7H4LIM'
  liquibase:
    enabled: true
    change-log: 'classpath:/db/changelog/liquibase.xml'
    default-schema: 'gamedata'
