/**
 *
 *  Activity.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace MaaGameData
{

class Activity
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _type;
        static const std::string _displayType;
        static const std::string _name;
        static const std::string _startTime;
        static const std::string _endTime;
        static const std::string _rewardEndTime;
        static const std::string _displayOnHome;
        static const std::string _hasStage;
        static const std::string _actTopBarColor;
        static const std::string _actTopBarText;
        static const std::string _templateShopId;
        static const std::string _medalGroupId;
        static const std::string _isReplicate;
        static const std::string _ungroupedMedalIds;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Activity(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Activity(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Activity(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Activity() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column type  */
    ///Get the value of the column type, returns the default value if the column is null
    const std::string &getValueOfType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getType() const noexcept;
    ///Set the value of the column type
    void setType(const std::string &pType) noexcept;
    void setType(std::string &&pType) noexcept;

    /**  For column displayType  */
    ///Get the value of the column displayType, returns the default value if the column is null
    const std::string &getValueOfDisplaytype() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDisplaytype() const noexcept;
    ///Set the value of the column displayType
    void setDisplaytype(const std::string &pDisplaytype) noexcept;
    void setDisplaytype(std::string &&pDisplaytype) noexcept;
    void setDisplaytypeToNull() noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column startTime  */
    ///Get the value of the column startTime, returns the default value if the column is null
    const int64_t &getValueOfStarttime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getStarttime() const noexcept;
    ///Set the value of the column startTime
    void setStarttime(const int64_t &pStarttime) noexcept;

    /**  For column endTime  */
    ///Get the value of the column endTime, returns the default value if the column is null
    const int64_t &getValueOfEndtime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getEndtime() const noexcept;
    ///Set the value of the column endTime
    void setEndtime(const int64_t &pEndtime) noexcept;

    /**  For column rewardEndTime  */
    ///Get the value of the column rewardEndTime, returns the default value if the column is null
    const int64_t &getValueOfRewardendtime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getRewardendtime() const noexcept;
    ///Set the value of the column rewardEndTime
    void setRewardendtime(const int64_t &pRewardendtime) noexcept;

    /**  For column displayOnHome  */
    ///Get the value of the column displayOnHome, returns the default value if the column is null
    const int8_t &getValueOfDisplayonhome() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getDisplayonhome() const noexcept;
    ///Set the value of the column displayOnHome
    void setDisplayonhome(const int8_t &pDisplayonhome) noexcept;

    /**  For column hasStage  */
    ///Get the value of the column hasStage, returns the default value if the column is null
    const int8_t &getValueOfHasstage() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getHasstage() const noexcept;
    ///Set the value of the column hasStage
    void setHasstage(const int8_t &pHasstage) noexcept;

    /**  For column actTopBarColor  */
    ///Get the value of the column actTopBarColor, returns the default value if the column is null
    const std::string &getValueOfActtopbarcolor() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getActtopbarcolor() const noexcept;
    ///Set the value of the column actTopBarColor
    void setActtopbarcolor(const std::string &pActtopbarcolor) noexcept;
    void setActtopbarcolor(std::string &&pActtopbarcolor) noexcept;
    void setActtopbarcolorToNull() noexcept;

    /**  For column actTopBarText  */
    ///Get the value of the column actTopBarText, returns the default value if the column is null
    const std::string &getValueOfActtopbartext() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getActtopbartext() const noexcept;
    ///Set the value of the column actTopBarText
    void setActtopbartext(const std::string &pActtopbartext) noexcept;
    void setActtopbartext(std::string &&pActtopbartext) noexcept;
    void setActtopbartextToNull() noexcept;

    /**  For column templateShopId  */
    ///Get the value of the column templateShopId, returns the default value if the column is null
    const std::string &getValueOfTemplateshopid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTemplateshopid() const noexcept;
    ///Set the value of the column templateShopId
    void setTemplateshopid(const std::string &pTemplateshopid) noexcept;
    void setTemplateshopid(std::string &&pTemplateshopid) noexcept;
    void setTemplateshopidToNull() noexcept;

    /**  For column medalGroupId  */
    ///Get the value of the column medalGroupId, returns the default value if the column is null
    const std::string &getValueOfMedalgroupid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMedalgroupid() const noexcept;
    ///Set the value of the column medalGroupId
    void setMedalgroupid(const std::string &pMedalgroupid) noexcept;
    void setMedalgroupid(std::string &&pMedalgroupid) noexcept;
    void setMedalgroupidToNull() noexcept;

    /**  For column isReplicate  */
    ///Get the value of the column isReplicate, returns the default value if the column is null
    const int8_t &getValueOfIsreplicate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getIsreplicate() const noexcept;
    ///Set the value of the column isReplicate
    void setIsreplicate(const int8_t &pIsreplicate) noexcept;

    /**  For column ungroupedMedalIds  */
    ///Get the value of the column ungroupedMedalIds, returns the default value if the column is null
    const std::string &getValueOfUngroupedmedalids() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUngroupedmedalids() const noexcept;
    ///Set the value of the column ungroupedMedalIds
    void setUngroupedmedalids(const std::string &pUngroupedmedalids) noexcept;
    void setUngroupedmedalids(std::string &&pUngroupedmedalids) noexcept;
    void setUngroupedmedalidsToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 15;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Activity>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Activity>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> type_;
    std::shared_ptr<std::string> displaytype_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<int64_t> starttime_;
    std::shared_ptr<int64_t> endtime_;
    std::shared_ptr<int64_t> rewardendtime_;
    std::shared_ptr<int8_t> displayonhome_;
    std::shared_ptr<int8_t> hasstage_;
    std::shared_ptr<std::string> acttopbarcolor_;
    std::shared_ptr<std::string> acttopbartext_;
    std::shared_ptr<std::string> templateshopid_;
    std::shared_ptr<std::string> medalgroupid_;
    std::shared_ptr<int8_t> isreplicate_;
    std::shared_ptr<std::string> ungroupedmedalids_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[15]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "type,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "displayType,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "startTime,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "endTime,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "rewardEndTime,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "displayOnHome,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "hasStage,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "actTopBarColor,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "actTopBarText,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "templateShopId,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "medalGroupId,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "isReplicate,";
            ++parametersCount;
        }
        if(dirtyFlag_[14])
        {
            sql += "ungroupedMedalIds,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[0])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[10])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[11])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[12])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[13])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[14])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace MaaGameData
} // namespace drogon_model
