/**
 *
 *  Activity.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Activity.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::MaaGameData::gamedata;

const std::string Activity::Cols::_id = "id";
const std::string Activity::Cols::_type = "type";
const std::string Activity::Cols::_displayType = "displayType";
const std::string Activity::Cols::_name = "name";
const std::string Activity::Cols::_startTime = "startTime";
const std::string Activity::Cols::_endTime = "endTime";
const std::string Activity::Cols::_rewardEndTime = "rewardEndTime";
const std::string Activity::Cols::_displayOnHome = "displayOnHome";
const std::string Activity::Cols::_hasStage = "hasStage";
const std::string Activity::Cols::_actTopBarColor = "actTopBarColor";
const std::string Activity::Cols::_actTopBarText = "actTopBarText";
const std::string Activity::Cols::_templateShopId = "templateShopId";
const std::string Activity::Cols::_medalGroupId = "medalGroupId";
const std::string Activity::Cols::_isReplicate = "isReplicate";
const std::string Activity::Cols::_ungroupedMedalIds = "ungroupedMedalIds";
const std::string Activity::primaryKeyName = "id";
const bool Activity::hasPrimaryKey = true;
const std::string Activity::tableName = "gamedata.activity";

const std::vector<typename Activity::MetaData> Activity::metaData_={
{"id","std::string","character varying",255,0,1,1},
{"type","std::string","character varying",255,0,0,1},
{"displayType","std::string","character varying",255,0,0,0},
{"name","std::string","character varying",255,0,0,1},
{"startTime","::trantor::Date","timestamp without time zone",0,0,0,1},
{"endTime","::trantor::Date","timestamp without time zone",0,0,0,1},
{"rewardEndTime","::trantor::Date","timestamp without time zone",0,0,0,1},
{"displayOnHome","bool","boolean",1,0,0,1},
{"hasStage","bool","boolean",1,0,0,1},
{"actTopBarColor","std::string","character varying",255,0,0,0},
{"actTopBarText","std::string","character varying",255,0,0,0},
{"templateShopId","std::string","character varying",255,0,0,0},
{"medalGroupId","std::string","character varying",255,0,0,0},
{"isReplicate","bool","boolean",1,0,0,1},
{"ungroupedMedalIds","std::string","json",0,0,0,0}
};
const std::string &Activity::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Activity::Activity(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["type"].isNull())
        {
            type_=std::make_shared<std::string>(r["type"].as<std::string>());
        }
        if(!r["displayType"].isNull())
        {
            displaytype_=std::make_shared<std::string>(r["displayType"].as<std::string>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["startTime"].isNull())
        {
            auto timeStr = r["startTime"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                starttime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["endTime"].isNull())
        {
            auto timeStr = r["endTime"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                endtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["rewardEndTime"].isNull())
        {
            auto timeStr = r["rewardEndTime"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                rewardendtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["displayOnHome"].isNull())
        {
            displayonhome_=std::make_shared<bool>(r["displayOnHome"].as<bool>());
        }
        if(!r["hasStage"].isNull())
        {
            hasstage_=std::make_shared<bool>(r["hasStage"].as<bool>());
        }
        if(!r["actTopBarColor"].isNull())
        {
            acttopbarcolor_=std::make_shared<std::string>(r["actTopBarColor"].as<std::string>());
        }
        if(!r["actTopBarText"].isNull())
        {
            acttopbartext_=std::make_shared<std::string>(r["actTopBarText"].as<std::string>());
        }
        if(!r["templateShopId"].isNull())
        {
            templateshopid_=std::make_shared<std::string>(r["templateShopId"].as<std::string>());
        }
        if(!r["medalGroupId"].isNull())
        {
            medalgroupid_=std::make_shared<std::string>(r["medalGroupId"].as<std::string>());
        }
        if(!r["isReplicate"].isNull())
        {
            isreplicate_=std::make_shared<bool>(r["isReplicate"].as<bool>());
        }
        if(!r["ungroupedMedalIds"].isNull())
        {
            ungroupedmedalids_=std::make_shared<std::string>(r["ungroupedMedalIds"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 15 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            type_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            displaytype_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                starttime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                endtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                rewardendtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            displayonhome_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            hasstage_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            acttopbarcolor_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            acttopbartext_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            templateshopid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            medalgroupid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            isreplicate_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            ungroupedmedalids_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Activity::Activity(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            type_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            displaytype_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                starttime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                endtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                rewardendtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            displayonhome_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            hasstage_=std::make_shared<bool>(pJson[pMasqueradingVector[8]].asBool());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            acttopbarcolor_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            acttopbartext_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            templateshopid_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            medalgroupid_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            isreplicate_=std::make_shared<bool>(pJson[pMasqueradingVector[13]].asBool());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            ungroupedmedalids_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
}

Activity::Activity(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("type"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["type"].isNull())
        {
            type_=std::make_shared<std::string>(pJson["type"].asString());
        }
    }
    if(pJson.isMember("displayType"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["displayType"].isNull())
        {
            displaytype_=std::make_shared<std::string>(pJson["displayType"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("startTime"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["startTime"].isNull())
        {
            auto timeStr = pJson["startTime"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                starttime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("endTime"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["endTime"].isNull())
        {
            auto timeStr = pJson["endTime"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                endtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("rewardEndTime"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["rewardEndTime"].isNull())
        {
            auto timeStr = pJson["rewardEndTime"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                rewardendtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("displayOnHome"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["displayOnHome"].isNull())
        {
            displayonhome_=std::make_shared<bool>(pJson["displayOnHome"].asBool());
        }
    }
    if(pJson.isMember("hasStage"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["hasStage"].isNull())
        {
            hasstage_=std::make_shared<bool>(pJson["hasStage"].asBool());
        }
    }
    if(pJson.isMember("actTopBarColor"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["actTopBarColor"].isNull())
        {
            acttopbarcolor_=std::make_shared<std::string>(pJson["actTopBarColor"].asString());
        }
    }
    if(pJson.isMember("actTopBarText"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["actTopBarText"].isNull())
        {
            acttopbartext_=std::make_shared<std::string>(pJson["actTopBarText"].asString());
        }
    }
    if(pJson.isMember("templateShopId"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["templateShopId"].isNull())
        {
            templateshopid_=std::make_shared<std::string>(pJson["templateShopId"].asString());
        }
    }
    if(pJson.isMember("medalGroupId"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["medalGroupId"].isNull())
        {
            medalgroupid_=std::make_shared<std::string>(pJson["medalGroupId"].asString());
        }
    }
    if(pJson.isMember("isReplicate"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["isReplicate"].isNull())
        {
            isreplicate_=std::make_shared<bool>(pJson["isReplicate"].asBool());
        }
    }
    if(pJson.isMember("ungroupedMedalIds"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["ungroupedMedalIds"].isNull())
        {
            ungroupedmedalids_=std::make_shared<std::string>(pJson["ungroupedMedalIds"].asString());
        }
    }
}

void Activity::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            type_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            displaytype_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                starttime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                endtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                rewardendtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            displayonhome_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            hasstage_=std::make_shared<bool>(pJson[pMasqueradingVector[8]].asBool());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            acttopbarcolor_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            acttopbartext_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            templateshopid_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            medalgroupid_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            isreplicate_=std::make_shared<bool>(pJson[pMasqueradingVector[13]].asBool());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            ungroupedmedalids_=std::make_shared<std::string>(pJson[pMasqueradingVector[14]].asString());
        }
    }
}

void Activity::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("type"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["type"].isNull())
        {
            type_=std::make_shared<std::string>(pJson["type"].asString());
        }
    }
    if(pJson.isMember("displayType"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["displayType"].isNull())
        {
            displaytype_=std::make_shared<std::string>(pJson["displayType"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("startTime"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["startTime"].isNull())
        {
            auto timeStr = pJson["startTime"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                starttime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("endTime"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["endTime"].isNull())
        {
            auto timeStr = pJson["endTime"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                endtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("rewardEndTime"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["rewardEndTime"].isNull())
        {
            auto timeStr = pJson["rewardEndTime"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                rewardendtime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("displayOnHome"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["displayOnHome"].isNull())
        {
            displayonhome_=std::make_shared<bool>(pJson["displayOnHome"].asBool());
        }
    }
    if(pJson.isMember("hasStage"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["hasStage"].isNull())
        {
            hasstage_=std::make_shared<bool>(pJson["hasStage"].asBool());
        }
    }
    if(pJson.isMember("actTopBarColor"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["actTopBarColor"].isNull())
        {
            acttopbarcolor_=std::make_shared<std::string>(pJson["actTopBarColor"].asString());
        }
    }
    if(pJson.isMember("actTopBarText"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["actTopBarText"].isNull())
        {
            acttopbartext_=std::make_shared<std::string>(pJson["actTopBarText"].asString());
        }
    }
    if(pJson.isMember("templateShopId"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["templateShopId"].isNull())
        {
            templateshopid_=std::make_shared<std::string>(pJson["templateShopId"].asString());
        }
    }
    if(pJson.isMember("medalGroupId"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["medalGroupId"].isNull())
        {
            medalgroupid_=std::make_shared<std::string>(pJson["medalGroupId"].asString());
        }
    }
    if(pJson.isMember("isReplicate"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["isReplicate"].isNull())
        {
            isreplicate_=std::make_shared<bool>(pJson["isReplicate"].asBool());
        }
    }
    if(pJson.isMember("ungroupedMedalIds"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["ungroupedMedalIds"].isNull())
        {
            ungroupedmedalids_=std::make_shared<std::string>(pJson["ungroupedMedalIds"].asString());
        }
    }
}

const std::string &Activity::getValueOfId() const noexcept
{
    const static std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getId() const noexcept
{
    return id_;
}
void Activity::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void Activity::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename Activity::PrimaryKeyType & Activity::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Activity::getValueOfType() const noexcept
{
    const static std::string defaultValue = std::string();
    if(type_)
        return *type_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getType() const noexcept
{
    return type_;
}
void Activity::setType(const std::string &pType) noexcept
{
    type_ = std::make_shared<std::string>(pType);
    dirtyFlag_[1] = true;
}
void Activity::setType(std::string &&pType) noexcept
{
    type_ = std::make_shared<std::string>(std::move(pType));
    dirtyFlag_[1] = true;
}

const std::string &Activity::getValueOfDisplaytype() const noexcept
{
    const static std::string defaultValue = std::string();
    if(displaytype_)
        return *displaytype_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getDisplaytype() const noexcept
{
    return displaytype_;
}
void Activity::setDisplaytype(const std::string &pDisplaytype) noexcept
{
    displaytype_ = std::make_shared<std::string>(pDisplaytype);
    dirtyFlag_[2] = true;
}
void Activity::setDisplaytype(std::string &&pDisplaytype) noexcept
{
    displaytype_ = std::make_shared<std::string>(std::move(pDisplaytype));
    dirtyFlag_[2] = true;
}
void Activity::setDisplaytypeToNull() noexcept
{
    displaytype_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Activity::getValueOfName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getName() const noexcept
{
    return name_;
}
void Activity::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[3] = true;
}
void Activity::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[3] = true;
}

const ::trantor::Date &Activity::getValueOfStarttime() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(starttime_)
        return *starttime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Activity::getStarttime() const noexcept
{
    return starttime_;
}
void Activity::setStarttime(const ::trantor::Date &pStarttime) noexcept
{
    starttime_ = std::make_shared<::trantor::Date>(pStarttime);
    dirtyFlag_[4] = true;
}

const ::trantor::Date &Activity::getValueOfEndtime() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(endtime_)
        return *endtime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Activity::getEndtime() const noexcept
{
    return endtime_;
}
void Activity::setEndtime(const ::trantor::Date &pEndtime) noexcept
{
    endtime_ = std::make_shared<::trantor::Date>(pEndtime);
    dirtyFlag_[5] = true;
}

const ::trantor::Date &Activity::getValueOfRewardendtime() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(rewardendtime_)
        return *rewardendtime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Activity::getRewardendtime() const noexcept
{
    return rewardendtime_;
}
void Activity::setRewardendtime(const ::trantor::Date &pRewardendtime) noexcept
{
    rewardendtime_ = std::make_shared<::trantor::Date>(pRewardendtime);
    dirtyFlag_[6] = true;
}

const bool &Activity::getValueOfDisplayonhome() const noexcept
{
    const static bool defaultValue = bool();
    if(displayonhome_)
        return *displayonhome_;
    return defaultValue;
}
const std::shared_ptr<bool> &Activity::getDisplayonhome() const noexcept
{
    return displayonhome_;
}
void Activity::setDisplayonhome(const bool &pDisplayonhome) noexcept
{
    displayonhome_ = std::make_shared<bool>(pDisplayonhome);
    dirtyFlag_[7] = true;
}

const bool &Activity::getValueOfHasstage() const noexcept
{
    const static bool defaultValue = bool();
    if(hasstage_)
        return *hasstage_;
    return defaultValue;
}
const std::shared_ptr<bool> &Activity::getHasstage() const noexcept
{
    return hasstage_;
}
void Activity::setHasstage(const bool &pHasstage) noexcept
{
    hasstage_ = std::make_shared<bool>(pHasstage);
    dirtyFlag_[8] = true;
}

const std::string &Activity::getValueOfActtopbarcolor() const noexcept
{
    const static std::string defaultValue = std::string();
    if(acttopbarcolor_)
        return *acttopbarcolor_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getActtopbarcolor() const noexcept
{
    return acttopbarcolor_;
}
void Activity::setActtopbarcolor(const std::string &pActtopbarcolor) noexcept
{
    acttopbarcolor_ = std::make_shared<std::string>(pActtopbarcolor);
    dirtyFlag_[9] = true;
}
void Activity::setActtopbarcolor(std::string &&pActtopbarcolor) noexcept
{
    acttopbarcolor_ = std::make_shared<std::string>(std::move(pActtopbarcolor));
    dirtyFlag_[9] = true;
}
void Activity::setActtopbarcolorToNull() noexcept
{
    acttopbarcolor_.reset();
    dirtyFlag_[9] = true;
}

const std::string &Activity::getValueOfActtopbartext() const noexcept
{
    const static std::string defaultValue = std::string();
    if(acttopbartext_)
        return *acttopbartext_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getActtopbartext() const noexcept
{
    return acttopbartext_;
}
void Activity::setActtopbartext(const std::string &pActtopbartext) noexcept
{
    acttopbartext_ = std::make_shared<std::string>(pActtopbartext);
    dirtyFlag_[10] = true;
}
void Activity::setActtopbartext(std::string &&pActtopbartext) noexcept
{
    acttopbartext_ = std::make_shared<std::string>(std::move(pActtopbartext));
    dirtyFlag_[10] = true;
}
void Activity::setActtopbartextToNull() noexcept
{
    acttopbartext_.reset();
    dirtyFlag_[10] = true;
}

const std::string &Activity::getValueOfTemplateshopid() const noexcept
{
    const static std::string defaultValue = std::string();
    if(templateshopid_)
        return *templateshopid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getTemplateshopid() const noexcept
{
    return templateshopid_;
}
void Activity::setTemplateshopid(const std::string &pTemplateshopid) noexcept
{
    templateshopid_ = std::make_shared<std::string>(pTemplateshopid);
    dirtyFlag_[11] = true;
}
void Activity::setTemplateshopid(std::string &&pTemplateshopid) noexcept
{
    templateshopid_ = std::make_shared<std::string>(std::move(pTemplateshopid));
    dirtyFlag_[11] = true;
}
void Activity::setTemplateshopidToNull() noexcept
{
    templateshopid_.reset();
    dirtyFlag_[11] = true;
}

const std::string &Activity::getValueOfMedalgroupid() const noexcept
{
    const static std::string defaultValue = std::string();
    if(medalgroupid_)
        return *medalgroupid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getMedalgroupid() const noexcept
{
    return medalgroupid_;
}
void Activity::setMedalgroupid(const std::string &pMedalgroupid) noexcept
{
    medalgroupid_ = std::make_shared<std::string>(pMedalgroupid);
    dirtyFlag_[12] = true;
}
void Activity::setMedalgroupid(std::string &&pMedalgroupid) noexcept
{
    medalgroupid_ = std::make_shared<std::string>(std::move(pMedalgroupid));
    dirtyFlag_[12] = true;
}
void Activity::setMedalgroupidToNull() noexcept
{
    medalgroupid_.reset();
    dirtyFlag_[12] = true;
}

const bool &Activity::getValueOfIsreplicate() const noexcept
{
    const static bool defaultValue = bool();
    if(isreplicate_)
        return *isreplicate_;
    return defaultValue;
}
const std::shared_ptr<bool> &Activity::getIsreplicate() const noexcept
{
    return isreplicate_;
}
void Activity::setIsreplicate(const bool &pIsreplicate) noexcept
{
    isreplicate_ = std::make_shared<bool>(pIsreplicate);
    dirtyFlag_[13] = true;
}

const std::string &Activity::getValueOfUngroupedmedalids() const noexcept
{
    const static std::string defaultValue = std::string();
    if(ungroupedmedalids_)
        return *ungroupedmedalids_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Activity::getUngroupedmedalids() const noexcept
{
    return ungroupedmedalids_;
}
void Activity::setUngroupedmedalids(const std::string &pUngroupedmedalids) noexcept
{
    ungroupedmedalids_ = std::make_shared<std::string>(pUngroupedmedalids);
    dirtyFlag_[14] = true;
}
void Activity::setUngroupedmedalids(std::string &&pUngroupedmedalids) noexcept
{
    ungroupedmedalids_ = std::make_shared<std::string>(std::move(pUngroupedmedalids));
    dirtyFlag_[14] = true;
}
void Activity::setUngroupedmedalidsToNull() noexcept
{
    ungroupedmedalids_.reset();
    dirtyFlag_[14] = true;
}

void Activity::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Activity::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "type",
        "displayType",
        "name",
        "startTime",
        "endTime",
        "rewardEndTime",
        "displayOnHome",
        "hasStage",
        "actTopBarColor",
        "actTopBarText",
        "templateShopId",
        "medalGroupId",
        "isReplicate",
        "ungroupedMedalIds"
    };
    return inCols;
}

void Activity::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getType())
        {
            binder << getValueOfType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDisplaytype())
        {
            binder << getValueOfDisplaytype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStarttime())
        {
            binder << getValueOfStarttime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEndtime())
        {
            binder << getValueOfEndtime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRewardendtime())
        {
            binder << getValueOfRewardendtime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDisplayonhome())
        {
            binder << getValueOfDisplayonhome();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getHasstage())
        {
            binder << getValueOfHasstage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getActtopbarcolor())
        {
            binder << getValueOfActtopbarcolor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getActtopbartext())
        {
            binder << getValueOfActtopbartext();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getTemplateshopid())
        {
            binder << getValueOfTemplateshopid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getMedalgroupid())
        {
            binder << getValueOfMedalgroupid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getIsreplicate())
        {
            binder << getValueOfIsreplicate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getUngroupedmedalids())
        {
            binder << getValueOfUngroupedmedalids();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Activity::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    return ret;
}

void Activity::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getType())
        {
            binder << getValueOfType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDisplaytype())
        {
            binder << getValueOfDisplaytype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStarttime())
        {
            binder << getValueOfStarttime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getEndtime())
        {
            binder << getValueOfEndtime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRewardendtime())
        {
            binder << getValueOfRewardendtime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDisplayonhome())
        {
            binder << getValueOfDisplayonhome();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getHasstage())
        {
            binder << getValueOfHasstage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getActtopbarcolor())
        {
            binder << getValueOfActtopbarcolor();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getActtopbartext())
        {
            binder << getValueOfActtopbartext();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getTemplateshopid())
        {
            binder << getValueOfTemplateshopid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getMedalgroupid())
        {
            binder << getValueOfMedalgroupid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getIsreplicate())
        {
            binder << getValueOfIsreplicate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getUngroupedmedalids())
        {
            binder << getValueOfUngroupedmedalids();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Activity::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getType())
    {
        ret["type"]=getValueOfType();
    }
    else
    {
        ret["type"]=Json::Value();
    }
    if(getDisplaytype())
    {
        ret["displayType"]=getValueOfDisplaytype();
    }
    else
    {
        ret["displayType"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getStarttime())
    {
        ret["startTime"]=getStarttime()->toDbStringLocal();
    }
    else
    {
        ret["startTime"]=Json::Value();
    }
    if(getEndtime())
    {
        ret["endTime"]=getEndtime()->toDbStringLocal();
    }
    else
    {
        ret["endTime"]=Json::Value();
    }
    if(getRewardendtime())
    {
        ret["rewardEndTime"]=getRewardendtime()->toDbStringLocal();
    }
    else
    {
        ret["rewardEndTime"]=Json::Value();
    }
    if(getDisplayonhome())
    {
        ret["displayOnHome"]=getValueOfDisplayonhome();
    }
    else
    {
        ret["displayOnHome"]=Json::Value();
    }
    if(getHasstage())
    {
        ret["hasStage"]=getValueOfHasstage();
    }
    else
    {
        ret["hasStage"]=Json::Value();
    }
    if(getActtopbarcolor())
    {
        ret["actTopBarColor"]=getValueOfActtopbarcolor();
    }
    else
    {
        ret["actTopBarColor"]=Json::Value();
    }
    if(getActtopbartext())
    {
        ret["actTopBarText"]=getValueOfActtopbartext();
    }
    else
    {
        ret["actTopBarText"]=Json::Value();
    }
    if(getTemplateshopid())
    {
        ret["templateShopId"]=getValueOfTemplateshopid();
    }
    else
    {
        ret["templateShopId"]=Json::Value();
    }
    if(getMedalgroupid())
    {
        ret["medalGroupId"]=getValueOfMedalgroupid();
    }
    else
    {
        ret["medalGroupId"]=Json::Value();
    }
    if(getIsreplicate())
    {
        ret["isReplicate"]=getValueOfIsreplicate();
    }
    else
    {
        ret["isReplicate"]=Json::Value();
    }
    if(getUngroupedmedalids())
    {
        ret["ungroupedMedalIds"]=getValueOfUngroupedmedalids();
    }
    else
    {
        ret["ungroupedMedalIds"]=Json::Value();
    }
    return ret;
}

Json::Value Activity::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 15)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getType())
            {
                ret[pMasqueradingVector[1]]=getValueOfType();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDisplaytype())
            {
                ret[pMasqueradingVector[2]]=getValueOfDisplaytype();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[3]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getStarttime())
            {
                ret[pMasqueradingVector[4]]=getStarttime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getEndtime())
            {
                ret[pMasqueradingVector[5]]=getEndtime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getRewardendtime())
            {
                ret[pMasqueradingVector[6]]=getRewardendtime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDisplayonhome())
            {
                ret[pMasqueradingVector[7]]=getValueOfDisplayonhome();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getHasstage())
            {
                ret[pMasqueradingVector[8]]=getValueOfHasstage();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getActtopbarcolor())
            {
                ret[pMasqueradingVector[9]]=getValueOfActtopbarcolor();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getActtopbartext())
            {
                ret[pMasqueradingVector[10]]=getValueOfActtopbartext();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getTemplateshopid())
            {
                ret[pMasqueradingVector[11]]=getValueOfTemplateshopid();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getMedalgroupid())
            {
                ret[pMasqueradingVector[12]]=getValueOfMedalgroupid();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getIsreplicate())
            {
                ret[pMasqueradingVector[13]]=getValueOfIsreplicate();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getUngroupedmedalids())
            {
                ret[pMasqueradingVector[14]]=getValueOfUngroupedmedalids();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getType())
    {
        ret["type"]=getValueOfType();
    }
    else
    {
        ret["type"]=Json::Value();
    }
    if(getDisplaytype())
    {
        ret["displayType"]=getValueOfDisplaytype();
    }
    else
    {
        ret["displayType"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getStarttime())
    {
        ret["startTime"]=getStarttime()->toDbStringLocal();
    }
    else
    {
        ret["startTime"]=Json::Value();
    }
    if(getEndtime())
    {
        ret["endTime"]=getEndtime()->toDbStringLocal();
    }
    else
    {
        ret["endTime"]=Json::Value();
    }
    if(getRewardendtime())
    {
        ret["rewardEndTime"]=getRewardendtime()->toDbStringLocal();
    }
    else
    {
        ret["rewardEndTime"]=Json::Value();
    }
    if(getDisplayonhome())
    {
        ret["displayOnHome"]=getValueOfDisplayonhome();
    }
    else
    {
        ret["displayOnHome"]=Json::Value();
    }
    if(getHasstage())
    {
        ret["hasStage"]=getValueOfHasstage();
    }
    else
    {
        ret["hasStage"]=Json::Value();
    }
    if(getActtopbarcolor())
    {
        ret["actTopBarColor"]=getValueOfActtopbarcolor();
    }
    else
    {
        ret["actTopBarColor"]=Json::Value();
    }
    if(getActtopbartext())
    {
        ret["actTopBarText"]=getValueOfActtopbartext();
    }
    else
    {
        ret["actTopBarText"]=Json::Value();
    }
    if(getTemplateshopid())
    {
        ret["templateShopId"]=getValueOfTemplateshopid();
    }
    else
    {
        ret["templateShopId"]=Json::Value();
    }
    if(getMedalgroupid())
    {
        ret["medalGroupId"]=getValueOfMedalgroupid();
    }
    else
    {
        ret["medalGroupId"]=Json::Value();
    }
    if(getIsreplicate())
    {
        ret["isReplicate"]=getValueOfIsreplicate();
    }
    else
    {
        ret["isReplicate"]=Json::Value();
    }
    if(getUngroupedmedalids())
    {
        ret["ungroupedMedalIds"]=getValueOfUngroupedmedalids();
    }
    else
    {
        ret["ungroupedMedalIds"]=Json::Value();
    }
    return ret;
}

bool Activity::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    else
    {
        err="The id column cannot be null";
        return false;
    }
    if(pJson.isMember("type"))
    {
        if(!validJsonOfField(1, "type", pJson["type"], err, true))
            return false;
    }
    else
    {
        err="The type column cannot be null";
        return false;
    }
    if(pJson.isMember("displayType"))
    {
        if(!validJsonOfField(2, "displayType", pJson["displayType"], err, true))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(3, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("startTime"))
    {
        if(!validJsonOfField(4, "startTime", pJson["startTime"], err, true))
            return false;
    }
    else
    {
        err="The startTime column cannot be null";
        return false;
    }
    if(pJson.isMember("endTime"))
    {
        if(!validJsonOfField(5, "endTime", pJson["endTime"], err, true))
            return false;
    }
    else
    {
        err="The endTime column cannot be null";
        return false;
    }
    if(pJson.isMember("rewardEndTime"))
    {
        if(!validJsonOfField(6, "rewardEndTime", pJson["rewardEndTime"], err, true))
            return false;
    }
    else
    {
        err="The rewardEndTime column cannot be null";
        return false;
    }
    if(pJson.isMember("displayOnHome"))
    {
        if(!validJsonOfField(7, "displayOnHome", pJson["displayOnHome"], err, true))
            return false;
    }
    else
    {
        err="The displayOnHome column cannot be null";
        return false;
    }
    if(pJson.isMember("hasStage"))
    {
        if(!validJsonOfField(8, "hasStage", pJson["hasStage"], err, true))
            return false;
    }
    else
    {
        err="The hasStage column cannot be null";
        return false;
    }
    if(pJson.isMember("actTopBarColor"))
    {
        if(!validJsonOfField(9, "actTopBarColor", pJson["actTopBarColor"], err, true))
            return false;
    }
    if(pJson.isMember("actTopBarText"))
    {
        if(!validJsonOfField(10, "actTopBarText", pJson["actTopBarText"], err, true))
            return false;
    }
    if(pJson.isMember("templateShopId"))
    {
        if(!validJsonOfField(11, "templateShopId", pJson["templateShopId"], err, true))
            return false;
    }
    if(pJson.isMember("medalGroupId"))
    {
        if(!validJsonOfField(12, "medalGroupId", pJson["medalGroupId"], err, true))
            return false;
    }
    if(pJson.isMember("isReplicate"))
    {
        if(!validJsonOfField(13, "isReplicate", pJson["isReplicate"], err, true))
            return false;
    }
    else
    {
        err="The isReplicate column cannot be null";
        return false;
    }
    if(pJson.isMember("ungroupedMedalIds"))
    {
        if(!validJsonOfField(14, "ungroupedMedalIds", pJson["ungroupedMedalIds"], err, true))
            return false;
    }
    return true;
}
bool Activity::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[13] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Activity::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("type"))
    {
        if(!validJsonOfField(1, "type", pJson["type"], err, false))
            return false;
    }
    if(pJson.isMember("displayType"))
    {
        if(!validJsonOfField(2, "displayType", pJson["displayType"], err, false))
            return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(3, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("startTime"))
    {
        if(!validJsonOfField(4, "startTime", pJson["startTime"], err, false))
            return false;
    }
    if(pJson.isMember("endTime"))
    {
        if(!validJsonOfField(5, "endTime", pJson["endTime"], err, false))
            return false;
    }
    if(pJson.isMember("rewardEndTime"))
    {
        if(!validJsonOfField(6, "rewardEndTime", pJson["rewardEndTime"], err, false))
            return false;
    }
    if(pJson.isMember("displayOnHome"))
    {
        if(!validJsonOfField(7, "displayOnHome", pJson["displayOnHome"], err, false))
            return false;
    }
    if(pJson.isMember("hasStage"))
    {
        if(!validJsonOfField(8, "hasStage", pJson["hasStage"], err, false))
            return false;
    }
    if(pJson.isMember("actTopBarColor"))
    {
        if(!validJsonOfField(9, "actTopBarColor", pJson["actTopBarColor"], err, false))
            return false;
    }
    if(pJson.isMember("actTopBarText"))
    {
        if(!validJsonOfField(10, "actTopBarText", pJson["actTopBarText"], err, false))
            return false;
    }
    if(pJson.isMember("templateShopId"))
    {
        if(!validJsonOfField(11, "templateShopId", pJson["templateShopId"], err, false))
            return false;
    }
    if(pJson.isMember("medalGroupId"))
    {
        if(!validJsonOfField(12, "medalGroupId", pJson["medalGroupId"], err, false))
            return false;
    }
    if(pJson.isMember("isReplicate"))
    {
        if(!validJsonOfField(13, "isReplicate", pJson["isReplicate"], err, false))
            return false;
    }
    if(pJson.isMember("ungroupedMedalIds"))
    {
        if(!validJsonOfField(14, "ungroupedMedalIds", pJson["ungroupedMedalIds"], err, false))
            return false;
    }
    return true;
}
bool Activity::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Activity::validJsonOfField(size_t index,
                                const std::string &fieldName,
                                const Json::Value &pJson,
                                std::string &err,
                                bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 13:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
