/**
 *
 *  Character.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace MaaGameData
{
namespace gamedata
{

class Character
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _name;
        static const std::string _description;
        static const std::string _canUseGeneralPotentialItem;
        static const std::string _potentialItemId;
        static const std::string _nationId;
        static const std::string _groupId;
        static const std::string _teamId;
        static const std::string _displayNumber;
        static const std::string _tokenKey;
        static const std::string _appellation;
        static const std::string _position;
        static const std::string _tagList;
        static const std::string _itemUsage;
        static const std::string _itemDesc;
        static const std::string _itemObtainApproach;
        static const std::string _isNotObtainable;
        static const std::string _isSpChar;
        static const std::string _maxPotentialLevel;
        static const std::string _rarity;
        static const std::string _profession;
        static const std::string _subProfessionId;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Character(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Character(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Character(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Character() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const std::string &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const std::string &pId) noexcept;
    void setId(std::string &&pId) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;

    /**  For column canUseGeneralPotentialItem  */
    ///Get the value of the column canUseGeneralPotentialItem, returns the default value if the column is null
    const bool &getValueOfCanusegeneralpotentialitem() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getCanusegeneralpotentialitem() const noexcept;
    ///Set the value of the column canUseGeneralPotentialItem
    void setCanusegeneralpotentialitem(const bool &pCanusegeneralpotentialitem) noexcept;

    /**  For column potentialItemId  */
    ///Get the value of the column potentialItemId, returns the default value if the column is null
    const std::string &getValueOfPotentialitemid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPotentialitemid() const noexcept;
    ///Set the value of the column potentialItemId
    void setPotentialitemid(const std::string &pPotentialitemid) noexcept;
    void setPotentialitemid(std::string &&pPotentialitemid) noexcept;

    /**  For column nationId  */
    ///Get the value of the column nationId, returns the default value if the column is null
    const std::string &getValueOfNationid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNationid() const noexcept;
    ///Set the value of the column nationId
    void setNationid(const std::string &pNationid) noexcept;
    void setNationid(std::string &&pNationid) noexcept;
    void setNationidToNull() noexcept;

    /**  For column groupId  */
    ///Get the value of the column groupId, returns the default value if the column is null
    const std::string &getValueOfGroupid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGroupid() const noexcept;
    ///Set the value of the column groupId
    void setGroupid(const std::string &pGroupid) noexcept;
    void setGroupid(std::string &&pGroupid) noexcept;
    void setGroupidToNull() noexcept;

    /**  For column teamId  */
    ///Get the value of the column teamId, returns the default value if the column is null
    const std::string &getValueOfTeamid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTeamid() const noexcept;
    ///Set the value of the column teamId
    void setTeamid(const std::string &pTeamid) noexcept;
    void setTeamid(std::string &&pTeamid) noexcept;
    void setTeamidToNull() noexcept;

    /**  For column displayNumber  */
    ///Get the value of the column displayNumber, returns the default value if the column is null
    const std::string &getValueOfDisplaynumber() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDisplaynumber() const noexcept;
    ///Set the value of the column displayNumber
    void setDisplaynumber(const std::string &pDisplaynumber) noexcept;
    void setDisplaynumber(std::string &&pDisplaynumber) noexcept;
    void setDisplaynumberToNull() noexcept;

    /**  For column tokenKey  */
    ///Get the value of the column tokenKey, returns the default value if the column is null
    const std::string &getValueOfTokenkey() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTokenkey() const noexcept;
    ///Set the value of the column tokenKey
    void setTokenkey(const std::string &pTokenkey) noexcept;
    void setTokenkey(std::string &&pTokenkey) noexcept;
    void setTokenkeyToNull() noexcept;

    /**  For column appellation  */
    ///Get the value of the column appellation, returns the default value if the column is null
    const std::string &getValueOfAppellation() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAppellation() const noexcept;
    ///Set the value of the column appellation
    void setAppellation(const std::string &pAppellation) noexcept;
    void setAppellation(std::string &&pAppellation) noexcept;

    /**  For column position  */
    ///Get the value of the column position, returns the default value if the column is null
    const std::string &getValueOfPosition() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPosition() const noexcept;
    ///Set the value of the column position
    void setPosition(const std::string &pPosition) noexcept;
    void setPosition(std::string &&pPosition) noexcept;

    /**  For column tagList  */
    ///Get the value of the column tagList, returns the default value if the column is null
    const std::string &getValueOfTaglist() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTaglist() const noexcept;
    ///Set the value of the column tagList
    void setTaglist(const std::string &pTaglist) noexcept;
    void setTaglist(std::string &&pTaglist) noexcept;

    /**  For column itemUsage  */
    ///Get the value of the column itemUsage, returns the default value if the column is null
    const std::string &getValueOfItemusage() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getItemusage() const noexcept;
    ///Set the value of the column itemUsage
    void setItemusage(const std::string &pItemusage) noexcept;
    void setItemusage(std::string &&pItemusage) noexcept;
    void setItemusageToNull() noexcept;

    /**  For column itemDesc  */
    ///Get the value of the column itemDesc, returns the default value if the column is null
    const std::string &getValueOfItemdesc() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getItemdesc() const noexcept;
    ///Set the value of the column itemDesc
    void setItemdesc(const std::string &pItemdesc) noexcept;
    void setItemdesc(std::string &&pItemdesc) noexcept;
    void setItemdescToNull() noexcept;

    /**  For column itemObtainApproach  */
    ///Get the value of the column itemObtainApproach, returns the default value if the column is null
    const std::string &getValueOfItemobtainapproach() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getItemobtainapproach() const noexcept;
    ///Set the value of the column itemObtainApproach
    void setItemobtainapproach(const std::string &pItemobtainapproach) noexcept;
    void setItemobtainapproach(std::string &&pItemobtainapproach) noexcept;
    void setItemobtainapproachToNull() noexcept;

    /**  For column isNotObtainable  */
    ///Get the value of the column isNotObtainable, returns the default value if the column is null
    const bool &getValueOfIsnotobtainable() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsnotobtainable() const noexcept;
    ///Set the value of the column isNotObtainable
    void setIsnotobtainable(const bool &pIsnotobtainable) noexcept;

    /**  For column isSpChar  */
    ///Get the value of the column isSpChar, returns the default value if the column is null
    const bool &getValueOfIsspchar() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsspchar() const noexcept;
    ///Set the value of the column isSpChar
    void setIsspchar(const bool &pIsspchar) noexcept;

    /**  For column maxPotentialLevel  */
    ///Get the value of the column maxPotentialLevel, returns the default value if the column is null
    const int32_t &getValueOfMaxpotentiallevel() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMaxpotentiallevel() const noexcept;
    ///Set the value of the column maxPotentialLevel
    void setMaxpotentiallevel(const int32_t &pMaxpotentiallevel) noexcept;

    /**  For column rarity  */
    ///Get the value of the column rarity, returns the default value if the column is null
    const int32_t &getValueOfRarity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getRarity() const noexcept;
    ///Set the value of the column rarity
    void setRarity(const int32_t &pRarity) noexcept;

    /**  For column profession  */
    ///Get the value of the column profession, returns the default value if the column is null
    const std::string &getValueOfProfession() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getProfession() const noexcept;
    ///Set the value of the column profession
    void setProfession(const std::string &pProfession) noexcept;
    void setProfession(std::string &&pProfession) noexcept;

    /**  For column subProfessionId  */
    ///Get the value of the column subProfessionId, returns the default value if the column is null
    const std::string &getValueOfSubprofessionid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSubprofessionid() const noexcept;
    ///Set the value of the column subProfessionId
    void setSubprofessionid(const std::string &pSubprofessionid) noexcept;
    void setSubprofessionid(std::string &&pSubprofessionid) noexcept;


    static size_t getColumnNumber() noexcept {  return 22;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Character>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Character>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> id_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<bool> canusegeneralpotentialitem_;
    std::shared_ptr<std::string> potentialitemid_;
    std::shared_ptr<std::string> nationid_;
    std::shared_ptr<std::string> groupid_;
    std::shared_ptr<std::string> teamid_;
    std::shared_ptr<std::string> displaynumber_;
    std::shared_ptr<std::string> tokenkey_;
    std::shared_ptr<std::string> appellation_;
    std::shared_ptr<std::string> position_;
    std::shared_ptr<std::string> taglist_;
    std::shared_ptr<std::string> itemusage_;
    std::shared_ptr<std::string> itemdesc_;
    std::shared_ptr<std::string> itemobtainapproach_;
    std::shared_ptr<bool> isnotobtainable_;
    std::shared_ptr<bool> isspchar_;
    std::shared_ptr<int32_t> maxpotentiallevel_;
    std::shared_ptr<int32_t> rarity_;
    std::shared_ptr<std::string> profession_;
    std::shared_ptr<std::string> subprofessionid_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[22]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "canUseGeneralPotentialItem,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "potentialItemId,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "nationId,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "groupId,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "teamId,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "displayNumber,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "tokenKey,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "appellation,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "position,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "tagList,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "itemUsage,";
            ++parametersCount;
        }
        if(dirtyFlag_[14])
        {
            sql += "itemDesc,";
            ++parametersCount;
        }
        if(dirtyFlag_[15])
        {
            sql += "itemObtainApproach,";
            ++parametersCount;
        }
        if(dirtyFlag_[16])
        {
            sql += "isNotObtainable,";
            ++parametersCount;
        }
        if(dirtyFlag_[17])
        {
            sql += "isSpChar,";
            ++parametersCount;
        }
        if(dirtyFlag_[18])
        {
            sql += "maxPotentialLevel,";
            ++parametersCount;
        }
        if(dirtyFlag_[19])
        {
            sql += "rarity,";
            ++parametersCount;
        }
        if(dirtyFlag_[20])
        {
            sql += "profession,";
            ++parametersCount;
        }
        if(dirtyFlag_[21])
        {
            sql += "subProfessionId,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[14])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[15])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[16])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[17])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[18])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[19])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[20])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[21])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace gamedata
} // namespace MaaGameData
} // namespace drogon_model
