/**
 *
 *  Item.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace MaaGameData
{
namespace gamedata
{

class Item
{
  public:
    struct Cols
    {
        static const std::string _itemId;
        static const std::string _name;
        static const std::string _description;
        static const std::string _rarity;
        static const std::string _iconId;
        static const std::string _overrideBkg;
        static const std::string _stackIconId;
        static const std::string _sortId;
        static const std::string _usage;
        static const std::string _obtainApproach;
        static const std::string _classifyType;
        static const std::string _itemType;
        static const std::string _stageDropList;
        static const std::string _buildingProductList;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Item(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Item(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Item(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Item() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column itemId  */
    ///Get the value of the column itemId, returns the default value if the column is null
    const std::string &getValueOfItemid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getItemid() const noexcept;
    ///Set the value of the column itemId
    void setItemid(const std::string &pItemid) noexcept;
    void setItemid(std::string &&pItemid) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;

    /**  For column rarity  */
    ///Get the value of the column rarity, returns the default value if the column is null
    const int32_t &getValueOfRarity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getRarity() const noexcept;
    ///Set the value of the column rarity
    void setRarity(const int32_t &pRarity) noexcept;

    /**  For column iconId  */
    ///Get the value of the column iconId, returns the default value if the column is null
    const std::string &getValueOfIconid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getIconid() const noexcept;
    ///Set the value of the column iconId
    void setIconid(const std::string &pIconid) noexcept;
    void setIconid(std::string &&pIconid) noexcept;

    /**  For column overrideBkg  */
    ///Get the value of the column overrideBkg, returns the default value if the column is null
    const std::string &getValueOfOverridebkg() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getOverridebkg() const noexcept;
    ///Set the value of the column overrideBkg
    void setOverridebkg(const std::string &pOverridebkg) noexcept;
    void setOverridebkg(std::string &&pOverridebkg) noexcept;
    void setOverridebkgToNull() noexcept;

    /**  For column stackIconId  */
    ///Get the value of the column stackIconId, returns the default value if the column is null
    const std::string &getValueOfStackiconid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStackiconid() const noexcept;
    ///Set the value of the column stackIconId
    void setStackiconid(const std::string &pStackiconid) noexcept;
    void setStackiconid(std::string &&pStackiconid) noexcept;
    void setStackiconidToNull() noexcept;

    /**  For column sortId  */
    ///Get the value of the column sortId, returns the default value if the column is null
    const int32_t &getValueOfSortid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getSortid() const noexcept;
    ///Set the value of the column sortId
    void setSortid(const int32_t &pSortid) noexcept;

    /**  For column usage  */
    ///Get the value of the column usage, returns the default value if the column is null
    const std::string &getValueOfUsage() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUsage() const noexcept;
    ///Set the value of the column usage
    void setUsage(const std::string &pUsage) noexcept;
    void setUsage(std::string &&pUsage) noexcept;

    /**  For column obtainApproach  */
    ///Get the value of the column obtainApproach, returns the default value if the column is null
    const std::string &getValueOfObtainapproach() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getObtainapproach() const noexcept;
    ///Set the value of the column obtainApproach
    void setObtainapproach(const std::string &pObtainapproach) noexcept;
    void setObtainapproach(std::string &&pObtainapproach) noexcept;
    void setObtainapproachToNull() noexcept;

    /**  For column classifyType  */
    ///Get the value of the column classifyType, returns the default value if the column is null
    const std::string &getValueOfClassifytype() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClassifytype() const noexcept;
    ///Set the value of the column classifyType
    void setClassifytype(const std::string &pClassifytype) noexcept;
    void setClassifytype(std::string &&pClassifytype) noexcept;

    /**  For column itemType  */
    ///Get the value of the column itemType, returns the default value if the column is null
    const std::string &getValueOfItemtype() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getItemtype() const noexcept;
    ///Set the value of the column itemType
    void setItemtype(const std::string &pItemtype) noexcept;
    void setItemtype(std::string &&pItemtype) noexcept;

    /**  For column stageDropList  */
    ///Get the value of the column stageDropList, returns the default value if the column is null
    const std::string &getValueOfStagedroplist() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStagedroplist() const noexcept;
    ///Set the value of the column stageDropList
    void setStagedroplist(const std::string &pStagedroplist) noexcept;
    void setStagedroplist(std::string &&pStagedroplist) noexcept;

    /**  For column buildingProductList  */
    ///Get the value of the column buildingProductList, returns the default value if the column is null
    const std::string &getValueOfBuildingproductlist() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBuildingproductlist() const noexcept;
    ///Set the value of the column buildingProductList
    void setBuildingproductlist(const std::string &pBuildingproductlist) noexcept;
    void setBuildingproductlist(std::string &&pBuildingproductlist) noexcept;


    static size_t getColumnNumber() noexcept {  return 14;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Item>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Item>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> itemid_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<int32_t> rarity_;
    std::shared_ptr<std::string> iconid_;
    std::shared_ptr<std::string> overridebkg_;
    std::shared_ptr<std::string> stackiconid_;
    std::shared_ptr<int32_t> sortid_;
    std::shared_ptr<std::string> usage_;
    std::shared_ptr<std::string> obtainapproach_;
    std::shared_ptr<std::string> classifytype_;
    std::shared_ptr<std::string> itemtype_;
    std::shared_ptr<std::string> stagedroplist_;
    std::shared_ptr<std::string> buildingproductlist_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[14]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where itemId = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where itemId = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "itemId,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "rarity,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "iconId,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "overrideBkg,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "stackIconId,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "sortId,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "usage,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "obtainApproach,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "classifyType,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "itemType,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "stageDropList,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "buildingProductList,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace gamedata
} // namespace MaaGameData
} // namespace drogon_model
