/**
 *
 *  Item.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Item.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::MaaGameData::gamedata;

const std::string Item::Cols::_itemId = "itemId";
const std::string Item::Cols::_name = "name";
const std::string Item::Cols::_description = "description";
const std::string Item::Cols::_rarity = "rarity";
const std::string Item::Cols::_iconId = "iconId";
const std::string Item::Cols::_overrideBkg = "overrideBkg";
const std::string Item::Cols::_stackIconId = "stackIconId";
const std::string Item::Cols::_sortId = "sortId";
const std::string Item::Cols::_usage = "usage";
const std::string Item::Cols::_obtainApproach = "obtainApproach";
const std::string Item::Cols::_classifyType = "classifyType";
const std::string Item::Cols::_itemType = "itemType";
const std::string Item::Cols::_stageDropList = "stageDropList";
const std::string Item::Cols::_buildingProductList = "buildingProductList";
const std::string Item::primaryKeyName = "itemId";
const bool Item::hasPrimaryKey = true;
const std::string Item::tableName = "gamedata.item";

const std::vector<typename Item::MetaData> Item::metaData_={
{"itemId","std::string","character varying",255,0,1,1},
{"name","std::string","character varying",255,0,0,1},
{"description","std::string","character varying",255,0,0,1},
{"rarity","int32_t","integer",4,0,0,1},
{"iconId","std::string","character varying",0,0,0,1},
{"overrideBkg","std::string","character varying",255,0,0,0},
{"stackIconId","std::string","character varying",0,0,0,0},
{"sortId","int32_t","integer",4,0,0,1},
{"usage","std::string","character varying",255,0,0,1},
{"obtainApproach","std::string","character varying",255,0,0,0},
{"classifyType","std::string","character varying",255,0,0,1},
{"itemType","std::string","character varying",255,0,0,1},
{"stageDropList","std::string","json",0,0,0,1},
{"buildingProductList","std::string","json",0,0,0,1}
};
const std::string &Item::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Item::Item(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["itemId"].isNull())
        {
            itemid_=std::make_shared<std::string>(r["itemId"].as<std::string>());
        }
        if(!r["name"].isNull())
        {
            name_=std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if(!r["description"].isNull())
        {
            description_=std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if(!r["rarity"].isNull())
        {
            rarity_=std::make_shared<int32_t>(r["rarity"].as<int32_t>());
        }
        if(!r["iconId"].isNull())
        {
            iconid_=std::make_shared<std::string>(r["iconId"].as<std::string>());
        }
        if(!r["overrideBkg"].isNull())
        {
            overridebkg_=std::make_shared<std::string>(r["overrideBkg"].as<std::string>());
        }
        if(!r["stackIconId"].isNull())
        {
            stackiconid_=std::make_shared<std::string>(r["stackIconId"].as<std::string>());
        }
        if(!r["sortId"].isNull())
        {
            sortid_=std::make_shared<int32_t>(r["sortId"].as<int32_t>());
        }
        if(!r["usage"].isNull())
        {
            usage_=std::make_shared<std::string>(r["usage"].as<std::string>());
        }
        if(!r["obtainApproach"].isNull())
        {
            obtainapproach_=std::make_shared<std::string>(r["obtainApproach"].as<std::string>());
        }
        if(!r["classifyType"].isNull())
        {
            classifytype_=std::make_shared<std::string>(r["classifyType"].as<std::string>());
        }
        if(!r["itemType"].isNull())
        {
            itemtype_=std::make_shared<std::string>(r["itemType"].as<std::string>());
        }
        if(!r["stageDropList"].isNull())
        {
            stagedroplist_=std::make_shared<std::string>(r["stageDropList"].as<std::string>());
        }
        if(!r["buildingProductList"].isNull())
        {
            buildingproductlist_=std::make_shared<std::string>(r["buildingProductList"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 14 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            itemid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            description_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            rarity_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            iconid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            overridebkg_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            stackiconid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            sortid_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            usage_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            obtainapproach_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            classifytype_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            itemtype_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            stagedroplist_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            buildingproductlist_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Item::Item(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            itemid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            rarity_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            iconid_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            overridebkg_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            stackiconid_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            sortid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            usage_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            obtainapproach_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            classifytype_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            itemtype_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            stagedroplist_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            buildingproductlist_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
}

Item::Item(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("itemId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["itemId"].isNull())
        {
            itemid_=std::make_shared<std::string>(pJson["itemId"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("rarity"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["rarity"].isNull())
        {
            rarity_=std::make_shared<int32_t>((int32_t)pJson["rarity"].asInt64());
        }
    }
    if(pJson.isMember("iconId"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["iconId"].isNull())
        {
            iconid_=std::make_shared<std::string>(pJson["iconId"].asString());
        }
    }
    if(pJson.isMember("overrideBkg"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["overrideBkg"].isNull())
        {
            overridebkg_=std::make_shared<std::string>(pJson["overrideBkg"].asString());
        }
    }
    if(pJson.isMember("stackIconId"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["stackIconId"].isNull())
        {
            stackiconid_=std::make_shared<std::string>(pJson["stackIconId"].asString());
        }
    }
    if(pJson.isMember("sortId"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["sortId"].isNull())
        {
            sortid_=std::make_shared<int32_t>((int32_t)pJson["sortId"].asInt64());
        }
    }
    if(pJson.isMember("usage"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["usage"].isNull())
        {
            usage_=std::make_shared<std::string>(pJson["usage"].asString());
        }
    }
    if(pJson.isMember("obtainApproach"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["obtainApproach"].isNull())
        {
            obtainapproach_=std::make_shared<std::string>(pJson["obtainApproach"].asString());
        }
    }
    if(pJson.isMember("classifyType"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["classifyType"].isNull())
        {
            classifytype_=std::make_shared<std::string>(pJson["classifyType"].asString());
        }
    }
    if(pJson.isMember("itemType"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["itemType"].isNull())
        {
            itemtype_=std::make_shared<std::string>(pJson["itemType"].asString());
        }
    }
    if(pJson.isMember("stageDropList"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["stageDropList"].isNull())
        {
            stagedroplist_=std::make_shared<std::string>(pJson["stageDropList"].asString());
        }
    }
    if(pJson.isMember("buildingProductList"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["buildingProductList"].isNull())
        {
            buildingproductlist_=std::make_shared<std::string>(pJson["buildingProductList"].asString());
        }
    }
}

void Item::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            itemid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            description_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            rarity_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            iconid_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            overridebkg_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            stackiconid_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            sortid_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            usage_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            obtainapproach_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            classifytype_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            itemtype_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            stagedroplist_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            buildingproductlist_=std::make_shared<std::string>(pJson[pMasqueradingVector[13]].asString());
        }
    }
}

void Item::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("itemId"))
    {
        if(!pJson["itemId"].isNull())
        {
            itemid_=std::make_shared<std::string>(pJson["itemId"].asString());
        }
    }
    if(pJson.isMember("name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if(pJson.isMember("description"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["description"].isNull())
        {
            description_=std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if(pJson.isMember("rarity"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["rarity"].isNull())
        {
            rarity_=std::make_shared<int32_t>((int32_t)pJson["rarity"].asInt64());
        }
    }
    if(pJson.isMember("iconId"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["iconId"].isNull())
        {
            iconid_=std::make_shared<std::string>(pJson["iconId"].asString());
        }
    }
    if(pJson.isMember("overrideBkg"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["overrideBkg"].isNull())
        {
            overridebkg_=std::make_shared<std::string>(pJson["overrideBkg"].asString());
        }
    }
    if(pJson.isMember("stackIconId"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["stackIconId"].isNull())
        {
            stackiconid_=std::make_shared<std::string>(pJson["stackIconId"].asString());
        }
    }
    if(pJson.isMember("sortId"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["sortId"].isNull())
        {
            sortid_=std::make_shared<int32_t>((int32_t)pJson["sortId"].asInt64());
        }
    }
    if(pJson.isMember("usage"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["usage"].isNull())
        {
            usage_=std::make_shared<std::string>(pJson["usage"].asString());
        }
    }
    if(pJson.isMember("obtainApproach"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["obtainApproach"].isNull())
        {
            obtainapproach_=std::make_shared<std::string>(pJson["obtainApproach"].asString());
        }
    }
    if(pJson.isMember("classifyType"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["classifyType"].isNull())
        {
            classifytype_=std::make_shared<std::string>(pJson["classifyType"].asString());
        }
    }
    if(pJson.isMember("itemType"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["itemType"].isNull())
        {
            itemtype_=std::make_shared<std::string>(pJson["itemType"].asString());
        }
    }
    if(pJson.isMember("stageDropList"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["stageDropList"].isNull())
        {
            stagedroplist_=std::make_shared<std::string>(pJson["stageDropList"].asString());
        }
    }
    if(pJson.isMember("buildingProductList"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["buildingProductList"].isNull())
        {
            buildingproductlist_=std::make_shared<std::string>(pJson["buildingProductList"].asString());
        }
    }
}

const std::string &Item::getValueOfItemid() const noexcept
{
    const static std::string defaultValue = std::string();
    if(itemid_)
        return *itemid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getItemid() const noexcept
{
    return itemid_;
}
void Item::setItemid(const std::string &pItemid) noexcept
{
    itemid_ = std::make_shared<std::string>(pItemid);
    dirtyFlag_[0] = true;
}
void Item::setItemid(std::string &&pItemid) noexcept
{
    itemid_ = std::make_shared<std::string>(std::move(pItemid));
    dirtyFlag_[0] = true;
}
const typename Item::PrimaryKeyType & Item::getPrimaryKey() const
{
    assert(itemid_);
    return *itemid_;
}

const std::string &Item::getValueOfName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getName() const noexcept
{
    return name_;
}
void Item::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Item::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}

const std::string &Item::getValueOfDescription() const noexcept
{
    const static std::string defaultValue = std::string();
    if(description_)
        return *description_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getDescription() const noexcept
{
    return description_;
}
void Item::setDescription(const std::string &pDescription) noexcept
{
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[2] = true;
}
void Item::setDescription(std::string &&pDescription) noexcept
{
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[2] = true;
}

const int32_t &Item::getValueOfRarity() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(rarity_)
        return *rarity_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Item::getRarity() const noexcept
{
    return rarity_;
}
void Item::setRarity(const int32_t &pRarity) noexcept
{
    rarity_ = std::make_shared<int32_t>(pRarity);
    dirtyFlag_[3] = true;
}

const std::string &Item::getValueOfIconid() const noexcept
{
    const static std::string defaultValue = std::string();
    if(iconid_)
        return *iconid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getIconid() const noexcept
{
    return iconid_;
}
void Item::setIconid(const std::string &pIconid) noexcept
{
    iconid_ = std::make_shared<std::string>(pIconid);
    dirtyFlag_[4] = true;
}
void Item::setIconid(std::string &&pIconid) noexcept
{
    iconid_ = std::make_shared<std::string>(std::move(pIconid));
    dirtyFlag_[4] = true;
}

const std::string &Item::getValueOfOverridebkg() const noexcept
{
    const static std::string defaultValue = std::string();
    if(overridebkg_)
        return *overridebkg_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getOverridebkg() const noexcept
{
    return overridebkg_;
}
void Item::setOverridebkg(const std::string &pOverridebkg) noexcept
{
    overridebkg_ = std::make_shared<std::string>(pOverridebkg);
    dirtyFlag_[5] = true;
}
void Item::setOverridebkg(std::string &&pOverridebkg) noexcept
{
    overridebkg_ = std::make_shared<std::string>(std::move(pOverridebkg));
    dirtyFlag_[5] = true;
}
void Item::setOverridebkgToNull() noexcept
{
    overridebkg_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Item::getValueOfStackiconid() const noexcept
{
    const static std::string defaultValue = std::string();
    if(stackiconid_)
        return *stackiconid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getStackiconid() const noexcept
{
    return stackiconid_;
}
void Item::setStackiconid(const std::string &pStackiconid) noexcept
{
    stackiconid_ = std::make_shared<std::string>(pStackiconid);
    dirtyFlag_[6] = true;
}
void Item::setStackiconid(std::string &&pStackiconid) noexcept
{
    stackiconid_ = std::make_shared<std::string>(std::move(pStackiconid));
    dirtyFlag_[6] = true;
}
void Item::setStackiconidToNull() noexcept
{
    stackiconid_.reset();
    dirtyFlag_[6] = true;
}

const int32_t &Item::getValueOfSortid() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(sortid_)
        return *sortid_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Item::getSortid() const noexcept
{
    return sortid_;
}
void Item::setSortid(const int32_t &pSortid) noexcept
{
    sortid_ = std::make_shared<int32_t>(pSortid);
    dirtyFlag_[7] = true;
}

const std::string &Item::getValueOfUsage() const noexcept
{
    const static std::string defaultValue = std::string();
    if(usage_)
        return *usage_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getUsage() const noexcept
{
    return usage_;
}
void Item::setUsage(const std::string &pUsage) noexcept
{
    usage_ = std::make_shared<std::string>(pUsage);
    dirtyFlag_[8] = true;
}
void Item::setUsage(std::string &&pUsage) noexcept
{
    usage_ = std::make_shared<std::string>(std::move(pUsage));
    dirtyFlag_[8] = true;
}

const std::string &Item::getValueOfObtainapproach() const noexcept
{
    const static std::string defaultValue = std::string();
    if(obtainapproach_)
        return *obtainapproach_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getObtainapproach() const noexcept
{
    return obtainapproach_;
}
void Item::setObtainapproach(const std::string &pObtainapproach) noexcept
{
    obtainapproach_ = std::make_shared<std::string>(pObtainapproach);
    dirtyFlag_[9] = true;
}
void Item::setObtainapproach(std::string &&pObtainapproach) noexcept
{
    obtainapproach_ = std::make_shared<std::string>(std::move(pObtainapproach));
    dirtyFlag_[9] = true;
}
void Item::setObtainapproachToNull() noexcept
{
    obtainapproach_.reset();
    dirtyFlag_[9] = true;
}

const std::string &Item::getValueOfClassifytype() const noexcept
{
    const static std::string defaultValue = std::string();
    if(classifytype_)
        return *classifytype_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getClassifytype() const noexcept
{
    return classifytype_;
}
void Item::setClassifytype(const std::string &pClassifytype) noexcept
{
    classifytype_ = std::make_shared<std::string>(pClassifytype);
    dirtyFlag_[10] = true;
}
void Item::setClassifytype(std::string &&pClassifytype) noexcept
{
    classifytype_ = std::make_shared<std::string>(std::move(pClassifytype));
    dirtyFlag_[10] = true;
}

const std::string &Item::getValueOfItemtype() const noexcept
{
    const static std::string defaultValue = std::string();
    if(itemtype_)
        return *itemtype_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getItemtype() const noexcept
{
    return itemtype_;
}
void Item::setItemtype(const std::string &pItemtype) noexcept
{
    itemtype_ = std::make_shared<std::string>(pItemtype);
    dirtyFlag_[11] = true;
}
void Item::setItemtype(std::string &&pItemtype) noexcept
{
    itemtype_ = std::make_shared<std::string>(std::move(pItemtype));
    dirtyFlag_[11] = true;
}

const std::string &Item::getValueOfStagedroplist() const noexcept
{
    const static std::string defaultValue = std::string();
    if(stagedroplist_)
        return *stagedroplist_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getStagedroplist() const noexcept
{
    return stagedroplist_;
}
void Item::setStagedroplist(const std::string &pStagedroplist) noexcept
{
    stagedroplist_ = std::make_shared<std::string>(pStagedroplist);
    dirtyFlag_[12] = true;
}
void Item::setStagedroplist(std::string &&pStagedroplist) noexcept
{
    stagedroplist_ = std::make_shared<std::string>(std::move(pStagedroplist));
    dirtyFlag_[12] = true;
}

const std::string &Item::getValueOfBuildingproductlist() const noexcept
{
    const static std::string defaultValue = std::string();
    if(buildingproductlist_)
        return *buildingproductlist_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Item::getBuildingproductlist() const noexcept
{
    return buildingproductlist_;
}
void Item::setBuildingproductlist(const std::string &pBuildingproductlist) noexcept
{
    buildingproductlist_ = std::make_shared<std::string>(pBuildingproductlist);
    dirtyFlag_[13] = true;
}
void Item::setBuildingproductlist(std::string &&pBuildingproductlist) noexcept
{
    buildingproductlist_ = std::make_shared<std::string>(std::move(pBuildingproductlist));
    dirtyFlag_[13] = true;
}

void Item::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Item::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "itemId",
        "name",
        "description",
        "rarity",
        "iconId",
        "overrideBkg",
        "stackIconId",
        "sortId",
        "usage",
        "obtainApproach",
        "classifyType",
        "itemType",
        "stageDropList",
        "buildingProductList"
    };
    return inCols;
}

void Item::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getItemid())
        {
            binder << getValueOfItemid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRarity())
        {
            binder << getValueOfRarity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIconid())
        {
            binder << getValueOfIconid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getOverridebkg())
        {
            binder << getValueOfOverridebkg();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStackiconid())
        {
            binder << getValueOfStackiconid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSortid())
        {
            binder << getValueOfSortid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getUsage())
        {
            binder << getValueOfUsage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getObtainapproach())
        {
            binder << getValueOfObtainapproach();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getClassifytype())
        {
            binder << getValueOfClassifytype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getItemtype())
        {
            binder << getValueOfItemtype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getStagedroplist())
        {
            binder << getValueOfStagedroplist();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getBuildingproductlist())
        {
            binder << getValueOfBuildingproductlist();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Item::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void Item::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getItemid())
        {
            binder << getValueOfItemid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDescription())
        {
            binder << getValueOfDescription();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRarity())
        {
            binder << getValueOfRarity();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIconid())
        {
            binder << getValueOfIconid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getOverridebkg())
        {
            binder << getValueOfOverridebkg();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStackiconid())
        {
            binder << getValueOfStackiconid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getSortid())
        {
            binder << getValueOfSortid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getUsage())
        {
            binder << getValueOfUsage();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getObtainapproach())
        {
            binder << getValueOfObtainapproach();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getClassifytype())
        {
            binder << getValueOfClassifytype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getItemtype())
        {
            binder << getValueOfItemtype();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getStagedroplist())
        {
            binder << getValueOfStagedroplist();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getBuildingproductlist())
        {
            binder << getValueOfBuildingproductlist();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Item::toJson() const
{
    Json::Value ret;
    if(getItemid())
    {
        ret["itemId"]=getValueOfItemid();
    }
    else
    {
        ret["itemId"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getRarity())
    {
        ret["rarity"]=getValueOfRarity();
    }
    else
    {
        ret["rarity"]=Json::Value();
    }
    if(getIconid())
    {
        ret["iconId"]=getValueOfIconid();
    }
    else
    {
        ret["iconId"]=Json::Value();
    }
    if(getOverridebkg())
    {
        ret["overrideBkg"]=getValueOfOverridebkg();
    }
    else
    {
        ret["overrideBkg"]=Json::Value();
    }
    if(getStackiconid())
    {
        ret["stackIconId"]=getValueOfStackiconid();
    }
    else
    {
        ret["stackIconId"]=Json::Value();
    }
    if(getSortid())
    {
        ret["sortId"]=getValueOfSortid();
    }
    else
    {
        ret["sortId"]=Json::Value();
    }
    if(getUsage())
    {
        ret["usage"]=getValueOfUsage();
    }
    else
    {
        ret["usage"]=Json::Value();
    }
    if(getObtainapproach())
    {
        ret["obtainApproach"]=getValueOfObtainapproach();
    }
    else
    {
        ret["obtainApproach"]=Json::Value();
    }
    if(getClassifytype())
    {
        ret["classifyType"]=getValueOfClassifytype();
    }
    else
    {
        ret["classifyType"]=Json::Value();
    }
    if(getItemtype())
    {
        ret["itemType"]=getValueOfItemtype();
    }
    else
    {
        ret["itemType"]=Json::Value();
    }
    if(getStagedroplist())
    {
        ret["stageDropList"]=getValueOfStagedroplist();
    }
    else
    {
        ret["stageDropList"]=Json::Value();
    }
    if(getBuildingproductlist())
    {
        ret["buildingProductList"]=getValueOfBuildingproductlist();
    }
    else
    {
        ret["buildingProductList"]=Json::Value();
    }
    return ret;
}

Json::Value Item::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 14)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getItemid())
            {
                ret[pMasqueradingVector[0]]=getValueOfItemid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDescription())
            {
                ret[pMasqueradingVector[2]]=getValueOfDescription();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRarity())
            {
                ret[pMasqueradingVector[3]]=getValueOfRarity();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getIconid())
            {
                ret[pMasqueradingVector[4]]=getValueOfIconid();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getOverridebkg())
            {
                ret[pMasqueradingVector[5]]=getValueOfOverridebkg();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getStackiconid())
            {
                ret[pMasqueradingVector[6]]=getValueOfStackiconid();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getSortid())
            {
                ret[pMasqueradingVector[7]]=getValueOfSortid();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getUsage())
            {
                ret[pMasqueradingVector[8]]=getValueOfUsage();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getObtainapproach())
            {
                ret[pMasqueradingVector[9]]=getValueOfObtainapproach();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getClassifytype())
            {
                ret[pMasqueradingVector[10]]=getValueOfClassifytype();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getItemtype())
            {
                ret[pMasqueradingVector[11]]=getValueOfItemtype();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getStagedroplist())
            {
                ret[pMasqueradingVector[12]]=getValueOfStagedroplist();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getBuildingproductlist())
            {
                ret[pMasqueradingVector[13]]=getValueOfBuildingproductlist();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getItemid())
    {
        ret["itemId"]=getValueOfItemid();
    }
    else
    {
        ret["itemId"]=Json::Value();
    }
    if(getName())
    {
        ret["name"]=getValueOfName();
    }
    else
    {
        ret["name"]=Json::Value();
    }
    if(getDescription())
    {
        ret["description"]=getValueOfDescription();
    }
    else
    {
        ret["description"]=Json::Value();
    }
    if(getRarity())
    {
        ret["rarity"]=getValueOfRarity();
    }
    else
    {
        ret["rarity"]=Json::Value();
    }
    if(getIconid())
    {
        ret["iconId"]=getValueOfIconid();
    }
    else
    {
        ret["iconId"]=Json::Value();
    }
    if(getOverridebkg())
    {
        ret["overrideBkg"]=getValueOfOverridebkg();
    }
    else
    {
        ret["overrideBkg"]=Json::Value();
    }
    if(getStackiconid())
    {
        ret["stackIconId"]=getValueOfStackiconid();
    }
    else
    {
        ret["stackIconId"]=Json::Value();
    }
    if(getSortid())
    {
        ret["sortId"]=getValueOfSortid();
    }
    else
    {
        ret["sortId"]=Json::Value();
    }
    if(getUsage())
    {
        ret["usage"]=getValueOfUsage();
    }
    else
    {
        ret["usage"]=Json::Value();
    }
    if(getObtainapproach())
    {
        ret["obtainApproach"]=getValueOfObtainapproach();
    }
    else
    {
        ret["obtainApproach"]=Json::Value();
    }
    if(getClassifytype())
    {
        ret["classifyType"]=getValueOfClassifytype();
    }
    else
    {
        ret["classifyType"]=Json::Value();
    }
    if(getItemtype())
    {
        ret["itemType"]=getValueOfItemtype();
    }
    else
    {
        ret["itemType"]=Json::Value();
    }
    if(getStagedroplist())
    {
        ret["stageDropList"]=getValueOfStagedroplist();
    }
    else
    {
        ret["stageDropList"]=Json::Value();
    }
    if(getBuildingproductlist())
    {
        ret["buildingProductList"]=getValueOfBuildingproductlist();
    }
    else
    {
        ret["buildingProductList"]=Json::Value();
    }
    return ret;
}

bool Item::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("itemId"))
    {
        if(!validJsonOfField(0, "itemId", pJson["itemId"], err, true))
            return false;
    }
    else
    {
        err="The itemId column cannot be null";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, true))
            return false;
    }
    else
    {
        err="The name column cannot be null";
        return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(2, "description", pJson["description"], err, true))
            return false;
    }
    else
    {
        err="The description column cannot be null";
        return false;
    }
    if(pJson.isMember("rarity"))
    {
        if(!validJsonOfField(3, "rarity", pJson["rarity"], err, true))
            return false;
    }
    else
    {
        err="The rarity column cannot be null";
        return false;
    }
    if(pJson.isMember("iconId"))
    {
        if(!validJsonOfField(4, "iconId", pJson["iconId"], err, true))
            return false;
    }
    else
    {
        err="The iconId column cannot be null";
        return false;
    }
    if(pJson.isMember("overrideBkg"))
    {
        if(!validJsonOfField(5, "overrideBkg", pJson["overrideBkg"], err, true))
            return false;
    }
    if(pJson.isMember("stackIconId"))
    {
        if(!validJsonOfField(6, "stackIconId", pJson["stackIconId"], err, true))
            return false;
    }
    if(pJson.isMember("sortId"))
    {
        if(!validJsonOfField(7, "sortId", pJson["sortId"], err, true))
            return false;
    }
    else
    {
        err="The sortId column cannot be null";
        return false;
    }
    if(pJson.isMember("usage"))
    {
        if(!validJsonOfField(8, "usage", pJson["usage"], err, true))
            return false;
    }
    else
    {
        err="The usage column cannot be null";
        return false;
    }
    if(pJson.isMember("obtainApproach"))
    {
        if(!validJsonOfField(9, "obtainApproach", pJson["obtainApproach"], err, true))
            return false;
    }
    if(pJson.isMember("classifyType"))
    {
        if(!validJsonOfField(10, "classifyType", pJson["classifyType"], err, true))
            return false;
    }
    else
    {
        err="The classifyType column cannot be null";
        return false;
    }
    if(pJson.isMember("itemType"))
    {
        if(!validJsonOfField(11, "itemType", pJson["itemType"], err, true))
            return false;
    }
    else
    {
        err="The itemType column cannot be null";
        return false;
    }
    if(pJson.isMember("stageDropList"))
    {
        if(!validJsonOfField(12, "stageDropList", pJson["stageDropList"], err, true))
            return false;
    }
    else
    {
        err="The stageDropList column cannot be null";
        return false;
    }
    if(pJson.isMember("buildingProductList"))
    {
        if(!validJsonOfField(13, "buildingProductList", pJson["buildingProductList"], err, true))
            return false;
    }
    else
    {
        err="The buildingProductList column cannot be null";
        return false;
    }
    return true;
}
bool Item::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[8] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[10] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[11] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[12] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[13] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Item::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("itemId"))
    {
        if(!validJsonOfField(0, "itemId", pJson["itemId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("name"))
    {
        if(!validJsonOfField(1, "name", pJson["name"], err, false))
            return false;
    }
    if(pJson.isMember("description"))
    {
        if(!validJsonOfField(2, "description", pJson["description"], err, false))
            return false;
    }
    if(pJson.isMember("rarity"))
    {
        if(!validJsonOfField(3, "rarity", pJson["rarity"], err, false))
            return false;
    }
    if(pJson.isMember("iconId"))
    {
        if(!validJsonOfField(4, "iconId", pJson["iconId"], err, false))
            return false;
    }
    if(pJson.isMember("overrideBkg"))
    {
        if(!validJsonOfField(5, "overrideBkg", pJson["overrideBkg"], err, false))
            return false;
    }
    if(pJson.isMember("stackIconId"))
    {
        if(!validJsonOfField(6, "stackIconId", pJson["stackIconId"], err, false))
            return false;
    }
    if(pJson.isMember("sortId"))
    {
        if(!validJsonOfField(7, "sortId", pJson["sortId"], err, false))
            return false;
    }
    if(pJson.isMember("usage"))
    {
        if(!validJsonOfField(8, "usage", pJson["usage"], err, false))
            return false;
    }
    if(pJson.isMember("obtainApproach"))
    {
        if(!validJsonOfField(9, "obtainApproach", pJson["obtainApproach"], err, false))
            return false;
    }
    if(pJson.isMember("classifyType"))
    {
        if(!validJsonOfField(10, "classifyType", pJson["classifyType"], err, false))
            return false;
    }
    if(pJson.isMember("itemType"))
    {
        if(!validJsonOfField(11, "itemType", pJson["itemType"], err, false))
            return false;
    }
    if(pJson.isMember("stageDropList"))
    {
        if(!validJsonOfField(12, "stageDropList", pJson["stageDropList"], err, false))
            return false;
    }
    if(pJson.isMember("buildingProductList"))
    {
        if(!validJsonOfField(13, "buildingProductList", pJson["buildingProductList"], err, false))
            return false;
    }
    return true;
}
bool Item::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector,
                                            std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Item::validJsonOfField(size_t index,
                            const std::string &fieldName,
                            const Json::Value &pJson,
                            std::string &err,
                            bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 10:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 11:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 12:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
