/**
 *
 *  Stage.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace MaaGameData
{
namespace gamedata
{

class Stage
{
  public:
    struct Cols
    {
        static const std::string _stageId;
        static const std::string _stageType;
        static const std::string _difficulty;
        static const std::string _performanceStageFlag;
        static const std::string _unlockCondition;
        static const std::string _levelId;
        static const std::string _zoneId;
        static const std::string _code;
        static const std::string _name;
        static const std::string _description;
        static const std::string _hardStageId;
        static const std::string _dangerLevel;
        static const std::string _dangerPoint;
        static const std::string _loadingPicId;
        static const std::string _canPractice;
        static const std::string _canBattleReplay;
        static const std::string _apCost;
        static const std::string _apFailReturn;
        static const std::string _etItemId;
        static const std::string _etCost;
        static const std::string _etFailReturn;
        static const std::string _etButtonStyle;
        static const std::string _apProtectTimes;
        static const std::string _diamondOnceDrop;
        static const std::string _practiceTicketCost;
        static const std::string _dailyStageDifficulty;
        static const std::string _expGain;
        static const std::string _goldGain;
        static const std::string _loseExpGain;
        static const std::string _loseGoldGain;
        static const std::string _passFavor;
        static const std::string _completeFavor;
        static const std::string _slProgress;
        static const std::string _displayMainItem;
        static const std::string _hilightMark;
        static const std::string _bossMark;
        static const std::string _isPredefined;
        static const std::string _isHardPredefined;
        static const std::string _isSkillSelectablePredefined;
        static const std::string _isStoryOnly;
        static const std::string _appearanceStyle;
        static const std::string _startButtonOverrideId;
        static const std::string _isStagePatch;
        static const std::string _mainStageId;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Stage(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Stage(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Stage(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Stage() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column stageId  */
    ///Get the value of the column stageId, returns the default value if the column is null
    const std::string &getValueOfStageid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStageid() const noexcept;
    ///Set the value of the column stageId
    void setStageid(const std::string &pStageid) noexcept;
    void setStageid(std::string &&pStageid) noexcept;

    /**  For column stageType  */
    ///Get the value of the column stageType, returns the default value if the column is null
    const std::string &getValueOfStagetype() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStagetype() const noexcept;
    ///Set the value of the column stageType
    void setStagetype(const std::string &pStagetype) noexcept;
    void setStagetype(std::string &&pStagetype) noexcept;
    void setStagetypeToNull() noexcept;

    /**  For column difficulty  */
    ///Get the value of the column difficulty, returns the default value if the column is null
    const std::string &getValueOfDifficulty() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDifficulty() const noexcept;
    ///Set the value of the column difficulty
    void setDifficulty(const std::string &pDifficulty) noexcept;
    void setDifficulty(std::string &&pDifficulty) noexcept;
    void setDifficultyToNull() noexcept;

    /**  For column performanceStageFlag  */
    ///Get the value of the column performanceStageFlag, returns the default value if the column is null
    const std::string &getValueOfPerformancestageflag() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPerformancestageflag() const noexcept;
    ///Set the value of the column performanceStageFlag
    void setPerformancestageflag(const std::string &pPerformancestageflag) noexcept;
    void setPerformancestageflag(std::string &&pPerformancestageflag) noexcept;
    void setPerformancestageflagToNull() noexcept;

    /**  For column unlockCondition  */
    ///Get the value of the column unlockCondition, returns the default value if the column is null
    const std::string &getValueOfUnlockcondition() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUnlockcondition() const noexcept;
    ///Set the value of the column unlockCondition
    void setUnlockcondition(const std::string &pUnlockcondition) noexcept;
    void setUnlockcondition(std::string &&pUnlockcondition) noexcept;
    void setUnlockconditionToNull() noexcept;

    /**  For column levelId  */
    ///Get the value of the column levelId, returns the default value if the column is null
    const std::string &getValueOfLevelid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLevelid() const noexcept;
    ///Set the value of the column levelId
    void setLevelid(const std::string &pLevelid) noexcept;
    void setLevelid(std::string &&pLevelid) noexcept;
    void setLevelidToNull() noexcept;

    /**  For column zoneId  */
    ///Get the value of the column zoneId, returns the default value if the column is null
    const std::string &getValueOfZoneid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getZoneid() const noexcept;
    ///Set the value of the column zoneId
    void setZoneid(const std::string &pZoneid) noexcept;
    void setZoneid(std::string &&pZoneid) noexcept;
    void setZoneidToNull() noexcept;

    /**  For column code  */
    ///Get the value of the column code, returns the default value if the column is null
    const std::string &getValueOfCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCode() const noexcept;
    ///Set the value of the column code
    void setCode(const std::string &pCode) noexcept;
    void setCode(std::string &&pCode) noexcept;
    void setCodeToNull() noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;
    void setNameToNull() noexcept;

    /**  For column description  */
    ///Get the value of the column description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;
    void setDescriptionToNull() noexcept;

    /**  For column hardStageId  */
    ///Get the value of the column hardStageId, returns the default value if the column is null
    const std::string &getValueOfHardstageid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getHardstageid() const noexcept;
    ///Set the value of the column hardStageId
    void setHardstageid(const std::string &pHardstageid) noexcept;
    void setHardstageid(std::string &&pHardstageid) noexcept;
    void setHardstageidToNull() noexcept;

    /**  For column dangerLevel  */
    ///Get the value of the column dangerLevel, returns the default value if the column is null
    const std::string &getValueOfDangerlevel() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDangerlevel() const noexcept;
    ///Set the value of the column dangerLevel
    void setDangerlevel(const std::string &pDangerlevel) noexcept;
    void setDangerlevel(std::string &&pDangerlevel) noexcept;
    void setDangerlevelToNull() noexcept;

    /**  For column dangerPoint  */
    ///Get the value of the column dangerPoint, returns the default value if the column is null
    const std::string &getValueOfDangerpoint() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDangerpoint() const noexcept;
    ///Set the value of the column dangerPoint
    void setDangerpoint(const std::string &pDangerpoint) noexcept;
    void setDangerpoint(std::string &&pDangerpoint) noexcept;
    void setDangerpointToNull() noexcept;

    /**  For column loadingPicId  */
    ///Get the value of the column loadingPicId, returns the default value if the column is null
    const std::string &getValueOfLoadingpicid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLoadingpicid() const noexcept;
    ///Set the value of the column loadingPicId
    void setLoadingpicid(const std::string &pLoadingpicid) noexcept;
    void setLoadingpicid(std::string &&pLoadingpicid) noexcept;
    void setLoadingpicidToNull() noexcept;

    /**  For column canPractice  */
    ///Get the value of the column canPractice, returns the default value if the column is null
    const bool &getValueOfCanpractice() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getCanpractice() const noexcept;
    ///Set the value of the column canPractice
    void setCanpractice(const bool &pCanpractice) noexcept;
    void setCanpracticeToNull() noexcept;

    /**  For column canBattleReplay  */
    ///Get the value of the column canBattleReplay, returns the default value if the column is null
    const bool &getValueOfCanbattlereplay() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getCanbattlereplay() const noexcept;
    ///Set the value of the column canBattleReplay
    void setCanbattlereplay(const bool &pCanbattlereplay) noexcept;
    void setCanbattlereplayToNull() noexcept;

    /**  For column apCost  */
    ///Get the value of the column apCost, returns the default value if the column is null
    const int32_t &getValueOfApcost() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getApcost() const noexcept;
    ///Set the value of the column apCost
    void setApcost(const int32_t &pApcost) noexcept;
    void setApcostToNull() noexcept;

    /**  For column apFailReturn  */
    ///Get the value of the column apFailReturn, returns the default value if the column is null
    const int32_t &getValueOfApfailreturn() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getApfailreturn() const noexcept;
    ///Set the value of the column apFailReturn
    void setApfailreturn(const int32_t &pApfailreturn) noexcept;
    void setApfailreturnToNull() noexcept;

    /**  For column etItemId  */
    ///Get the value of the column etItemId, returns the default value if the column is null
    const std::string &getValueOfEtitemid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEtitemid() const noexcept;
    ///Set the value of the column etItemId
    void setEtitemid(const std::string &pEtitemid) noexcept;
    void setEtitemid(std::string &&pEtitemid) noexcept;
    void setEtitemidToNull() noexcept;

    /**  For column etCost  */
    ///Get the value of the column etCost, returns the default value if the column is null
    const int32_t &getValueOfEtcost() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getEtcost() const noexcept;
    ///Set the value of the column etCost
    void setEtcost(const int32_t &pEtcost) noexcept;
    void setEtcostToNull() noexcept;

    /**  For column etFailReturn  */
    ///Get the value of the column etFailReturn, returns the default value if the column is null
    const int32_t &getValueOfEtfailreturn() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getEtfailreturn() const noexcept;
    ///Set the value of the column etFailReturn
    void setEtfailreturn(const int32_t &pEtfailreturn) noexcept;
    void setEtfailreturnToNull() noexcept;

    /**  For column etButtonStyle  */
    ///Get the value of the column etButtonStyle, returns the default value if the column is null
    const std::string &getValueOfEtbuttonstyle() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEtbuttonstyle() const noexcept;
    ///Set the value of the column etButtonStyle
    void setEtbuttonstyle(const std::string &pEtbuttonstyle) noexcept;
    void setEtbuttonstyle(std::string &&pEtbuttonstyle) noexcept;
    void setEtbuttonstyleToNull() noexcept;

    /**  For column apProtectTimes  */
    ///Get the value of the column apProtectTimes, returns the default value if the column is null
    const int32_t &getValueOfApprotecttimes() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getApprotecttimes() const noexcept;
    ///Set the value of the column apProtectTimes
    void setApprotecttimes(const int32_t &pApprotecttimes) noexcept;
    void setApprotecttimesToNull() noexcept;

    /**  For column diamondOnceDrop  */
    ///Get the value of the column diamondOnceDrop, returns the default value if the column is null
    const int32_t &getValueOfDiamondoncedrop() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getDiamondoncedrop() const noexcept;
    ///Set the value of the column diamondOnceDrop
    void setDiamondoncedrop(const int32_t &pDiamondoncedrop) noexcept;
    void setDiamondoncedropToNull() noexcept;

    /**  For column practiceTicketCost  */
    ///Get the value of the column practiceTicketCost, returns the default value if the column is null
    const int32_t &getValueOfPracticeticketcost() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getPracticeticketcost() const noexcept;
    ///Set the value of the column practiceTicketCost
    void setPracticeticketcost(const int32_t &pPracticeticketcost) noexcept;
    void setPracticeticketcostToNull() noexcept;

    /**  For column dailyStageDifficulty  */
    ///Get the value of the column dailyStageDifficulty, returns the default value if the column is null
    const int32_t &getValueOfDailystagedifficulty() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getDailystagedifficulty() const noexcept;
    ///Set the value of the column dailyStageDifficulty
    void setDailystagedifficulty(const int32_t &pDailystagedifficulty) noexcept;
    void setDailystagedifficultyToNull() noexcept;

    /**  For column expGain  */
    ///Get the value of the column expGain, returns the default value if the column is null
    const int32_t &getValueOfExpgain() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getExpgain() const noexcept;
    ///Set the value of the column expGain
    void setExpgain(const int32_t &pExpgain) noexcept;
    void setExpgainToNull() noexcept;

    /**  For column goldGain  */
    ///Get the value of the column goldGain, returns the default value if the column is null
    const int32_t &getValueOfGoldgain() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getGoldgain() const noexcept;
    ///Set the value of the column goldGain
    void setGoldgain(const int32_t &pGoldgain) noexcept;
    void setGoldgainToNull() noexcept;

    /**  For column loseExpGain  */
    ///Get the value of the column loseExpGain, returns the default value if the column is null
    const int32_t &getValueOfLoseexpgain() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getLoseexpgain() const noexcept;
    ///Set the value of the column loseExpGain
    void setLoseexpgain(const int32_t &pLoseexpgain) noexcept;
    void setLoseexpgainToNull() noexcept;

    /**  For column loseGoldGain  */
    ///Get the value of the column loseGoldGain, returns the default value if the column is null
    const int32_t &getValueOfLosegoldgain() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getLosegoldgain() const noexcept;
    ///Set the value of the column loseGoldGain
    void setLosegoldgain(const int32_t &pLosegoldgain) noexcept;
    void setLosegoldgainToNull() noexcept;

    /**  For column passFavor  */
    ///Get the value of the column passFavor, returns the default value if the column is null
    const int32_t &getValueOfPassfavor() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getPassfavor() const noexcept;
    ///Set the value of the column passFavor
    void setPassfavor(const int32_t &pPassfavor) noexcept;
    void setPassfavorToNull() noexcept;

    /**  For column completeFavor  */
    ///Get the value of the column completeFavor, returns the default value if the column is null
    const int32_t &getValueOfCompletefavor() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getCompletefavor() const noexcept;
    ///Set the value of the column completeFavor
    void setCompletefavor(const int32_t &pCompletefavor) noexcept;
    void setCompletefavorToNull() noexcept;

    /**  For column slProgress  */
    ///Get the value of the column slProgress, returns the default value if the column is null
    const int32_t &getValueOfSlprogress() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getSlprogress() const noexcept;
    ///Set the value of the column slProgress
    void setSlprogress(const int32_t &pSlprogress) noexcept;
    void setSlprogressToNull() noexcept;

    /**  For column displayMainItem  */
    ///Get the value of the column displayMainItem, returns the default value if the column is null
    const std::string &getValueOfDisplaymainitem() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDisplaymainitem() const noexcept;
    ///Set the value of the column displayMainItem
    void setDisplaymainitem(const std::string &pDisplaymainitem) noexcept;
    void setDisplaymainitem(std::string &&pDisplaymainitem) noexcept;
    void setDisplaymainitemToNull() noexcept;

    /**  For column hilightMark  */
    ///Get the value of the column hilightMark, returns the default value if the column is null
    const bool &getValueOfHilightmark() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getHilightmark() const noexcept;
    ///Set the value of the column hilightMark
    void setHilightmark(const bool &pHilightmark) noexcept;
    void setHilightmarkToNull() noexcept;

    /**  For column bossMark  */
    ///Get the value of the column bossMark, returns the default value if the column is null
    const bool &getValueOfBossmark() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getBossmark() const noexcept;
    ///Set the value of the column bossMark
    void setBossmark(const bool &pBossmark) noexcept;
    void setBossmarkToNull() noexcept;

    /**  For column isPredefined  */
    ///Get the value of the column isPredefined, returns the default value if the column is null
    const bool &getValueOfIspredefined() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIspredefined() const noexcept;
    ///Set the value of the column isPredefined
    void setIspredefined(const bool &pIspredefined) noexcept;
    void setIspredefinedToNull() noexcept;

    /**  For column isHardPredefined  */
    ///Get the value of the column isHardPredefined, returns the default value if the column is null
    const bool &getValueOfIshardpredefined() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIshardpredefined() const noexcept;
    ///Set the value of the column isHardPredefined
    void setIshardpredefined(const bool &pIshardpredefined) noexcept;
    void setIshardpredefinedToNull() noexcept;

    /**  For column isSkillSelectablePredefined  */
    ///Get the value of the column isSkillSelectablePredefined, returns the default value if the column is null
    const bool &getValueOfIsskillselectablepredefined() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsskillselectablepredefined() const noexcept;
    ///Set the value of the column isSkillSelectablePredefined
    void setIsskillselectablepredefined(const bool &pIsskillselectablepredefined) noexcept;
    void setIsskillselectablepredefinedToNull() noexcept;

    /**  For column isStoryOnly  */
    ///Get the value of the column isStoryOnly, returns the default value if the column is null
    const bool &getValueOfIsstoryonly() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsstoryonly() const noexcept;
    ///Set the value of the column isStoryOnly
    void setIsstoryonly(const bool &pIsstoryonly) noexcept;
    void setIsstoryonlyToNull() noexcept;

    /**  For column appearanceStyle  */
    ///Get the value of the column appearanceStyle, returns the default value if the column is null
    const int32_t &getValueOfAppearancestyle() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getAppearancestyle() const noexcept;
    ///Set the value of the column appearanceStyle
    void setAppearancestyle(const int32_t &pAppearancestyle) noexcept;
    void setAppearancestyleToNull() noexcept;

    /**  For column startButtonOverrideId  */
    ///Get the value of the column startButtonOverrideId, returns the default value if the column is null
    const std::string &getValueOfStartbuttonoverrideid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStartbuttonoverrideid() const noexcept;
    ///Set the value of the column startButtonOverrideId
    void setStartbuttonoverrideid(const std::string &pStartbuttonoverrideid) noexcept;
    void setStartbuttonoverrideid(std::string &&pStartbuttonoverrideid) noexcept;
    void setStartbuttonoverrideidToNull() noexcept;

    /**  For column isStagePatch  */
    ///Get the value of the column isStagePatch, returns the default value if the column is null
    const bool &getValueOfIsstagepatch() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getIsstagepatch() const noexcept;
    ///Set the value of the column isStagePatch
    void setIsstagepatch(const bool &pIsstagepatch) noexcept;
    void setIsstagepatchToNull() noexcept;

    /**  For column mainStageId  */
    ///Get the value of the column mainStageId, returns the default value if the column is null
    const std::string &getValueOfMainstageid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getMainstageid() const noexcept;
    ///Set the value of the column mainStageId
    void setMainstageid(const std::string &pMainstageid) noexcept;
    void setMainstageid(std::string &&pMainstageid) noexcept;
    void setMainstageidToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 44;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Stage>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Stage>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> stageid_;
    std::shared_ptr<std::string> stagetype_;
    std::shared_ptr<std::string> difficulty_;
    std::shared_ptr<std::string> performancestageflag_;
    std::shared_ptr<std::string> unlockcondition_;
    std::shared_ptr<std::string> levelid_;
    std::shared_ptr<std::string> zoneid_;
    std::shared_ptr<std::string> code_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<std::string> hardstageid_;
    std::shared_ptr<std::string> dangerlevel_;
    std::shared_ptr<std::string> dangerpoint_;
    std::shared_ptr<std::string> loadingpicid_;
    std::shared_ptr<bool> canpractice_;
    std::shared_ptr<bool> canbattlereplay_;
    std::shared_ptr<int32_t> apcost_;
    std::shared_ptr<int32_t> apfailreturn_;
    std::shared_ptr<std::string> etitemid_;
    std::shared_ptr<int32_t> etcost_;
    std::shared_ptr<int32_t> etfailreturn_;
    std::shared_ptr<std::string> etbuttonstyle_;
    std::shared_ptr<int32_t> approtecttimes_;
    std::shared_ptr<int32_t> diamondoncedrop_;
    std::shared_ptr<int32_t> practiceticketcost_;
    std::shared_ptr<int32_t> dailystagedifficulty_;
    std::shared_ptr<int32_t> expgain_;
    std::shared_ptr<int32_t> goldgain_;
    std::shared_ptr<int32_t> loseexpgain_;
    std::shared_ptr<int32_t> losegoldgain_;
    std::shared_ptr<int32_t> passfavor_;
    std::shared_ptr<int32_t> completefavor_;
    std::shared_ptr<int32_t> slprogress_;
    std::shared_ptr<std::string> displaymainitem_;
    std::shared_ptr<bool> hilightmark_;
    std::shared_ptr<bool> bossmark_;
    std::shared_ptr<bool> ispredefined_;
    std::shared_ptr<bool> ishardpredefined_;
    std::shared_ptr<bool> isskillselectablepredefined_;
    std::shared_ptr<bool> isstoryonly_;
    std::shared_ptr<int32_t> appearancestyle_;
    std::shared_ptr<std::string> startbuttonoverrideid_;
    std::shared_ptr<bool> isstagepatch_;
    std::shared_ptr<std::string> mainstageid_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[44]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where stageId = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where stageId = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "stageId,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "stageType,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "difficulty,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "performanceStageFlag,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "unlockCondition,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "levelId,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "zoneId,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "code,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "description,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "hardStageId,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "dangerLevel,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "dangerPoint,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "loadingPicId,";
            ++parametersCount;
        }
        if(dirtyFlag_[14])
        {
            sql += "canPractice,";
            ++parametersCount;
        }
        if(dirtyFlag_[15])
        {
            sql += "canBattleReplay,";
            ++parametersCount;
        }
        if(dirtyFlag_[16])
        {
            sql += "apCost,";
            ++parametersCount;
        }
        if(dirtyFlag_[17])
        {
            sql += "apFailReturn,";
            ++parametersCount;
        }
        if(dirtyFlag_[18])
        {
            sql += "etItemId,";
            ++parametersCount;
        }
        if(dirtyFlag_[19])
        {
            sql += "etCost,";
            ++parametersCount;
        }
        if(dirtyFlag_[20])
        {
            sql += "etFailReturn,";
            ++parametersCount;
        }
        if(dirtyFlag_[21])
        {
            sql += "etButtonStyle,";
            ++parametersCount;
        }
        if(dirtyFlag_[22])
        {
            sql += "apProtectTimes,";
            ++parametersCount;
        }
        if(dirtyFlag_[23])
        {
            sql += "diamondOnceDrop,";
            ++parametersCount;
        }
        if(dirtyFlag_[24])
        {
            sql += "practiceTicketCost,";
            ++parametersCount;
        }
        if(dirtyFlag_[25])
        {
            sql += "dailyStageDifficulty,";
            ++parametersCount;
        }
        if(dirtyFlag_[26])
        {
            sql += "expGain,";
            ++parametersCount;
        }
        if(dirtyFlag_[27])
        {
            sql += "goldGain,";
            ++parametersCount;
        }
        if(dirtyFlag_[28])
        {
            sql += "loseExpGain,";
            ++parametersCount;
        }
        if(dirtyFlag_[29])
        {
            sql += "loseGoldGain,";
            ++parametersCount;
        }
        if(dirtyFlag_[30])
        {
            sql += "passFavor,";
            ++parametersCount;
        }
        if(dirtyFlag_[31])
        {
            sql += "completeFavor,";
            ++parametersCount;
        }
        if(dirtyFlag_[32])
        {
            sql += "slProgress,";
            ++parametersCount;
        }
        if(dirtyFlag_[33])
        {
            sql += "displayMainItem,";
            ++parametersCount;
        }
        if(dirtyFlag_[34])
        {
            sql += "hilightMark,";
            ++parametersCount;
        }
        if(dirtyFlag_[35])
        {
            sql += "bossMark,";
            ++parametersCount;
        }
        if(dirtyFlag_[36])
        {
            sql += "isPredefined,";
            ++parametersCount;
        }
        if(dirtyFlag_[37])
        {
            sql += "isHardPredefined,";
            ++parametersCount;
        }
        if(dirtyFlag_[38])
        {
            sql += "isSkillSelectablePredefined,";
            ++parametersCount;
        }
        if(dirtyFlag_[39])
        {
            sql += "isStoryOnly,";
            ++parametersCount;
        }
        if(dirtyFlag_[40])
        {
            sql += "appearanceStyle,";
            ++parametersCount;
        }
        if(dirtyFlag_[41])
        {
            sql += "startButtonOverrideId,";
            ++parametersCount;
        }
        if(dirtyFlag_[42])
        {
            sql += "isStagePatch,";
            ++parametersCount;
        }
        if(dirtyFlag_[43])
        {
            sql += "mainStageId,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[14])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[15])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[16])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[17])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[18])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[19])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[20])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[21])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[22])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[23])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[24])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[25])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[26])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[27])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[28])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[29])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[30])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[31])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[32])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[33])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[34])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[35])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[36])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[37])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[38])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[39])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[40])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[41])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[42])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[43])
        {
            n = sprintf(placeholderStr,"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace gamedata
} // namespace MaaGameData
} // namespace drogon_model
