/**
 *
 *  Zone.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Zone.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::MaaGameData::gamedata;

const std::string Zone::Cols::_zoneId = "zoneId";
const std::string Zone::Cols::_zoneIndex = "zoneIndex";
const std::string Zone::Cols::_type = "type";
const std::string Zone::Cols::_zoneNameFirst = "zoneNameFirst";
const std::string Zone::Cols::_zoneNameSecond = "zoneNameSecond";
const std::string Zone::Cols::_zoneNameTitleCurrent = "zoneNameTitleCurrent";
const std::string Zone::Cols::_zoneNameTitleUncurrent = "zoneNameTitleUncurrent";
const std::string Zone::Cols::_zoneNameTitleEx = "zoneNameTitleEx";
const std::string Zone::Cols::_zoneNameThird = "zoneNameThird";
const std::string Zone::Cols::_lockedText = "lockedText";
const std::string Zone::Cols::_canPreview = "canPreview";
const std::string Zone::primaryKeyName = "zoneId";
const bool Zone::hasPrimaryKey = true;
const std::string Zone::tableName = "gamedata.zone";

const std::vector<typename Zone::MetaData> Zone::metaData_={
{"zoneId","std::string","character varying",0,0,1,1},
{"zoneIndex","int32_t","integer",4,0,0,0},
{"type","std::string","character varying",255,0,0,0},
{"zoneNameFirst","std::string","character varying",255,0,0,0},
{"zoneNameSecond","std::string","character varying",255,0,0,0},
{"zoneNameTitleCurrent","std::string","character varying",255,0,0,0},
{"zoneNameTitleUncurrent","std::string","character varying",255,0,0,0},
{"zoneNameTitleEx","std::string","character varying",255,0,0,0},
{"zoneNameThird","std::string","character varying",255,0,0,0},
{"lockedText","std::string","character varying",255,0,0,0},
{"canPreview","bool","boolean",1,0,0,0}
};
const std::string &Zone::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Zone::Zone(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["zoneId"].isNull())
        {
            zoneid_=std::make_shared<std::string>(r["zoneId"].as<std::string>());
        }
        if(!r["zoneIndex"].isNull())
        {
            zoneindex_=std::make_shared<int32_t>(r["zoneIndex"].as<int32_t>());
        }
        if(!r["type"].isNull())
        {
            type_=std::make_shared<std::string>(r["type"].as<std::string>());
        }
        if(!r["zoneNameFirst"].isNull())
        {
            zonenamefirst_=std::make_shared<std::string>(r["zoneNameFirst"].as<std::string>());
        }
        if(!r["zoneNameSecond"].isNull())
        {
            zonenamesecond_=std::make_shared<std::string>(r["zoneNameSecond"].as<std::string>());
        }
        if(!r["zoneNameTitleCurrent"].isNull())
        {
            zonenametitlecurrent_=std::make_shared<std::string>(r["zoneNameTitleCurrent"].as<std::string>());
        }
        if(!r["zoneNameTitleUncurrent"].isNull())
        {
            zonenametitleuncurrent_=std::make_shared<std::string>(r["zoneNameTitleUncurrent"].as<std::string>());
        }
        if(!r["zoneNameTitleEx"].isNull())
        {
            zonenametitleex_=std::make_shared<std::string>(r["zoneNameTitleEx"].as<std::string>());
        }
        if(!r["zoneNameThird"].isNull())
        {
            zonenamethird_=std::make_shared<std::string>(r["zoneNameThird"].as<std::string>());
        }
        if(!r["lockedText"].isNull())
        {
            lockedtext_=std::make_shared<std::string>(r["lockedText"].as<std::string>());
        }
        if(!r["canPreview"].isNull())
        {
            canpreview_=std::make_shared<bool>(r["canPreview"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            zoneid_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            zoneindex_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            type_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            zonenamefirst_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            zonenamesecond_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            zonenametitlecurrent_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            zonenametitleuncurrent_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            zonenametitleex_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            zonenamethird_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            lockedtext_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            canpreview_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

Zone::Zone(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            zoneid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            zoneindex_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            type_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            zonenamefirst_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            zonenamesecond_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            zonenametitlecurrent_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            zonenametitleuncurrent_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            zonenametitleex_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            zonenamethird_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            lockedtext_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            canpreview_=std::make_shared<bool>(pJson[pMasqueradingVector[10]].asBool());
        }
    }
}

Zone::Zone(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("zoneId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["zoneId"].isNull())
        {
            zoneid_=std::make_shared<std::string>(pJson["zoneId"].asString());
        }
    }
    if(pJson.isMember("zoneIndex"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["zoneIndex"].isNull())
        {
            zoneindex_=std::make_shared<int32_t>((int32_t)pJson["zoneIndex"].asInt64());
        }
    }
    if(pJson.isMember("type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["type"].isNull())
        {
            type_=std::make_shared<std::string>(pJson["type"].asString());
        }
    }
    if(pJson.isMember("zoneNameFirst"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["zoneNameFirst"].isNull())
        {
            zonenamefirst_=std::make_shared<std::string>(pJson["zoneNameFirst"].asString());
        }
    }
    if(pJson.isMember("zoneNameSecond"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["zoneNameSecond"].isNull())
        {
            zonenamesecond_=std::make_shared<std::string>(pJson["zoneNameSecond"].asString());
        }
    }
    if(pJson.isMember("zoneNameTitleCurrent"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["zoneNameTitleCurrent"].isNull())
        {
            zonenametitlecurrent_=std::make_shared<std::string>(pJson["zoneNameTitleCurrent"].asString());
        }
    }
    if(pJson.isMember("zoneNameTitleUncurrent"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["zoneNameTitleUncurrent"].isNull())
        {
            zonenametitleuncurrent_=std::make_shared<std::string>(pJson["zoneNameTitleUncurrent"].asString());
        }
    }
    if(pJson.isMember("zoneNameTitleEx"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["zoneNameTitleEx"].isNull())
        {
            zonenametitleex_=std::make_shared<std::string>(pJson["zoneNameTitleEx"].asString());
        }
    }
    if(pJson.isMember("zoneNameThird"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["zoneNameThird"].isNull())
        {
            zonenamethird_=std::make_shared<std::string>(pJson["zoneNameThird"].asString());
        }
    }
    if(pJson.isMember("lockedText"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["lockedText"].isNull())
        {
            lockedtext_=std::make_shared<std::string>(pJson["lockedText"].asString());
        }
    }
    if(pJson.isMember("canPreview"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["canPreview"].isNull())
        {
            canpreview_=std::make_shared<bool>(pJson["canPreview"].asBool());
        }
    }
}

void Zone::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            zoneid_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            zoneindex_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            type_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            zonenamefirst_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            zonenamesecond_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            zonenametitlecurrent_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            zonenametitleuncurrent_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            zonenametitleex_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            zonenamethird_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            lockedtext_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            canpreview_=std::make_shared<bool>(pJson[pMasqueradingVector[10]].asBool());
        }
    }
}

void Zone::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("zoneId"))
    {
        if(!pJson["zoneId"].isNull())
        {
            zoneid_=std::make_shared<std::string>(pJson["zoneId"].asString());
        }
    }
    if(pJson.isMember("zoneIndex"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["zoneIndex"].isNull())
        {
            zoneindex_=std::make_shared<int32_t>((int32_t)pJson["zoneIndex"].asInt64());
        }
    }
    if(pJson.isMember("type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["type"].isNull())
        {
            type_=std::make_shared<std::string>(pJson["type"].asString());
        }
    }
    if(pJson.isMember("zoneNameFirst"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["zoneNameFirst"].isNull())
        {
            zonenamefirst_=std::make_shared<std::string>(pJson["zoneNameFirst"].asString());
        }
    }
    if(pJson.isMember("zoneNameSecond"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["zoneNameSecond"].isNull())
        {
            zonenamesecond_=std::make_shared<std::string>(pJson["zoneNameSecond"].asString());
        }
    }
    if(pJson.isMember("zoneNameTitleCurrent"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["zoneNameTitleCurrent"].isNull())
        {
            zonenametitlecurrent_=std::make_shared<std::string>(pJson["zoneNameTitleCurrent"].asString());
        }
    }
    if(pJson.isMember("zoneNameTitleUncurrent"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["zoneNameTitleUncurrent"].isNull())
        {
            zonenametitleuncurrent_=std::make_shared<std::string>(pJson["zoneNameTitleUncurrent"].asString());
        }
    }
    if(pJson.isMember("zoneNameTitleEx"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["zoneNameTitleEx"].isNull())
        {
            zonenametitleex_=std::make_shared<std::string>(pJson["zoneNameTitleEx"].asString());
        }
    }
    if(pJson.isMember("zoneNameThird"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["zoneNameThird"].isNull())
        {
            zonenamethird_=std::make_shared<std::string>(pJson["zoneNameThird"].asString());
        }
    }
    if(pJson.isMember("lockedText"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["lockedText"].isNull())
        {
            lockedtext_=std::make_shared<std::string>(pJson["lockedText"].asString());
        }
    }
    if(pJson.isMember("canPreview"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["canPreview"].isNull())
        {
            canpreview_=std::make_shared<bool>(pJson["canPreview"].asBool());
        }
    }
}

const std::string &Zone::getValueOfZoneid() const noexcept
{
    const static std::string defaultValue = std::string();
    if(zoneid_)
        return *zoneid_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getZoneid() const noexcept
{
    return zoneid_;
}
void Zone::setZoneid(const std::string &pZoneid) noexcept
{
    zoneid_ = std::make_shared<std::string>(pZoneid);
    dirtyFlag_[0] = true;
}
void Zone::setZoneid(std::string &&pZoneid) noexcept
{
    zoneid_ = std::make_shared<std::string>(std::move(pZoneid));
    dirtyFlag_[0] = true;
}
const typename Zone::PrimaryKeyType & Zone::getPrimaryKey() const
{
    assert(zoneid_);
    return *zoneid_;
}

const int32_t &Zone::getValueOfZoneindex() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(zoneindex_)
        return *zoneindex_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Zone::getZoneindex() const noexcept
{
    return zoneindex_;
}
void Zone::setZoneindex(const int32_t &pZoneindex) noexcept
{
    zoneindex_ = std::make_shared<int32_t>(pZoneindex);
    dirtyFlag_[1] = true;
}
void Zone::setZoneindexToNull() noexcept
{
    zoneindex_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Zone::getValueOfType() const noexcept
{
    const static std::string defaultValue = std::string();
    if(type_)
        return *type_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getType() const noexcept
{
    return type_;
}
void Zone::setType(const std::string &pType) noexcept
{
    type_ = std::make_shared<std::string>(pType);
    dirtyFlag_[2] = true;
}
void Zone::setType(std::string &&pType) noexcept
{
    type_ = std::make_shared<std::string>(std::move(pType));
    dirtyFlag_[2] = true;
}
void Zone::setTypeToNull() noexcept
{
    type_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Zone::getValueOfZonenamefirst() const noexcept
{
    const static std::string defaultValue = std::string();
    if(zonenamefirst_)
        return *zonenamefirst_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getZonenamefirst() const noexcept
{
    return zonenamefirst_;
}
void Zone::setZonenamefirst(const std::string &pZonenamefirst) noexcept
{
    zonenamefirst_ = std::make_shared<std::string>(pZonenamefirst);
    dirtyFlag_[3] = true;
}
void Zone::setZonenamefirst(std::string &&pZonenamefirst) noexcept
{
    zonenamefirst_ = std::make_shared<std::string>(std::move(pZonenamefirst));
    dirtyFlag_[3] = true;
}
void Zone::setZonenamefirstToNull() noexcept
{
    zonenamefirst_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Zone::getValueOfZonenamesecond() const noexcept
{
    const static std::string defaultValue = std::string();
    if(zonenamesecond_)
        return *zonenamesecond_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getZonenamesecond() const noexcept
{
    return zonenamesecond_;
}
void Zone::setZonenamesecond(const std::string &pZonenamesecond) noexcept
{
    zonenamesecond_ = std::make_shared<std::string>(pZonenamesecond);
    dirtyFlag_[4] = true;
}
void Zone::setZonenamesecond(std::string &&pZonenamesecond) noexcept
{
    zonenamesecond_ = std::make_shared<std::string>(std::move(pZonenamesecond));
    dirtyFlag_[4] = true;
}
void Zone::setZonenamesecondToNull() noexcept
{
    zonenamesecond_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Zone::getValueOfZonenametitlecurrent() const noexcept
{
    const static std::string defaultValue = std::string();
    if(zonenametitlecurrent_)
        return *zonenametitlecurrent_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getZonenametitlecurrent() const noexcept
{
    return zonenametitlecurrent_;
}
void Zone::setZonenametitlecurrent(const std::string &pZonenametitlecurrent) noexcept
{
    zonenametitlecurrent_ = std::make_shared<std::string>(pZonenametitlecurrent);
    dirtyFlag_[5] = true;
}
void Zone::setZonenametitlecurrent(std::string &&pZonenametitlecurrent) noexcept
{
    zonenametitlecurrent_ = std::make_shared<std::string>(std::move(pZonenametitlecurrent));
    dirtyFlag_[5] = true;
}
void Zone::setZonenametitlecurrentToNull() noexcept
{
    zonenametitlecurrent_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Zone::getValueOfZonenametitleuncurrent() const noexcept
{
    const static std::string defaultValue = std::string();
    if(zonenametitleuncurrent_)
        return *zonenametitleuncurrent_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getZonenametitleuncurrent() const noexcept
{
    return zonenametitleuncurrent_;
}
void Zone::setZonenametitleuncurrent(const std::string &pZonenametitleuncurrent) noexcept
{
    zonenametitleuncurrent_ = std::make_shared<std::string>(pZonenametitleuncurrent);
    dirtyFlag_[6] = true;
}
void Zone::setZonenametitleuncurrent(std::string &&pZonenametitleuncurrent) noexcept
{
    zonenametitleuncurrent_ = std::make_shared<std::string>(std::move(pZonenametitleuncurrent));
    dirtyFlag_[6] = true;
}
void Zone::setZonenametitleuncurrentToNull() noexcept
{
    zonenametitleuncurrent_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Zone::getValueOfZonenametitleex() const noexcept
{
    const static std::string defaultValue = std::string();
    if(zonenametitleex_)
        return *zonenametitleex_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getZonenametitleex() const noexcept
{
    return zonenametitleex_;
}
void Zone::setZonenametitleex(const std::string &pZonenametitleex) noexcept
{
    zonenametitleex_ = std::make_shared<std::string>(pZonenametitleex);
    dirtyFlag_[7] = true;
}
void Zone::setZonenametitleex(std::string &&pZonenametitleex) noexcept
{
    zonenametitleex_ = std::make_shared<std::string>(std::move(pZonenametitleex));
    dirtyFlag_[7] = true;
}
void Zone::setZonenametitleexToNull() noexcept
{
    zonenametitleex_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Zone::getValueOfZonenamethird() const noexcept
{
    const static std::string defaultValue = std::string();
    if(zonenamethird_)
        return *zonenamethird_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getZonenamethird() const noexcept
{
    return zonenamethird_;
}
void Zone::setZonenamethird(const std::string &pZonenamethird) noexcept
{
    zonenamethird_ = std::make_shared<std::string>(pZonenamethird);
    dirtyFlag_[8] = true;
}
void Zone::setZonenamethird(std::string &&pZonenamethird) noexcept
{
    zonenamethird_ = std::make_shared<std::string>(std::move(pZonenamethird));
    dirtyFlag_[8] = true;
}
void Zone::setZonenamethirdToNull() noexcept
{
    zonenamethird_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Zone::getValueOfLockedtext() const noexcept
{
    const static std::string defaultValue = std::string();
    if(lockedtext_)
        return *lockedtext_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Zone::getLockedtext() const noexcept
{
    return lockedtext_;
}
void Zone::setLockedtext(const std::string &pLockedtext) noexcept
{
    lockedtext_ = std::make_shared<std::string>(pLockedtext);
    dirtyFlag_[9] = true;
}
void Zone::setLockedtext(std::string &&pLockedtext) noexcept
{
    lockedtext_ = std::make_shared<std::string>(std::move(pLockedtext));
    dirtyFlag_[9] = true;
}
void Zone::setLockedtextToNull() noexcept
{
    lockedtext_.reset();
    dirtyFlag_[9] = true;
}

const bool &Zone::getValueOfCanpreview() const noexcept
{
    const static bool defaultValue = bool();
    if(canpreview_)
        return *canpreview_;
    return defaultValue;
}
const std::shared_ptr<bool> &Zone::getCanpreview() const noexcept
{
    return canpreview_;
}
void Zone::setCanpreview(const bool &pCanpreview) noexcept
{
    canpreview_ = std::make_shared<bool>(pCanpreview);
    dirtyFlag_[10] = true;
}
void Zone::setCanpreviewToNull() noexcept
{
    canpreview_.reset();
    dirtyFlag_[10] = true;
}

void Zone::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Zone::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "zoneId",
        "zoneIndex",
        "type",
        "zoneNameFirst",
        "zoneNameSecond",
        "zoneNameTitleCurrent",
        "zoneNameTitleUncurrent",
        "zoneNameTitleEx",
        "zoneNameThird",
        "lockedText",
        "canPreview"
    };
    return inCols;
}

void Zone::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getZoneid())
        {
            binder << getValueOfZoneid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getZoneindex())
        {
            binder << getValueOfZoneindex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getType())
        {
            binder << getValueOfType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getZonenamefirst())
        {
            binder << getValueOfZonenamefirst();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getZonenamesecond())
        {
            binder << getValueOfZonenamesecond();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getZonenametitlecurrent())
        {
            binder << getValueOfZonenametitlecurrent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getZonenametitleuncurrent())
        {
            binder << getValueOfZonenametitleuncurrent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getZonenametitleex())
        {
            binder << getValueOfZonenametitleex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getZonenamethird())
        {
            binder << getValueOfZonenamethird();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLockedtext())
        {
            binder << getValueOfLockedtext();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCanpreview())
        {
            binder << getValueOfCanpreview();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Zone::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void Zone::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getZoneid())
        {
            binder << getValueOfZoneid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getZoneindex())
        {
            binder << getValueOfZoneindex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getType())
        {
            binder << getValueOfType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getZonenamefirst())
        {
            binder << getValueOfZonenamefirst();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getZonenamesecond())
        {
            binder << getValueOfZonenamesecond();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getZonenametitlecurrent())
        {
            binder << getValueOfZonenametitlecurrent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getZonenametitleuncurrent())
        {
            binder << getValueOfZonenametitleuncurrent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getZonenametitleex())
        {
            binder << getValueOfZonenametitleex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getZonenamethird())
        {
            binder << getValueOfZonenamethird();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getLockedtext())
        {
            binder << getValueOfLockedtext();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCanpreview())
        {
            binder << getValueOfCanpreview();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Zone::toJson() const
{
    Json::Value ret;
    if(getZoneid())
    {
        ret["zoneId"]=getValueOfZoneid();
    }
    else
    {
        ret["zoneId"]=Json::Value();
    }
    if(getZoneindex())
    {
        ret["zoneIndex"]=getValueOfZoneindex();
    }
    else
    {
        ret["zoneIndex"]=Json::Value();
    }
    if(getType())
    {
        ret["type"]=getValueOfType();
    }
    else
    {
        ret["type"]=Json::Value();
    }
    if(getZonenamefirst())
    {
        ret["zoneNameFirst"]=getValueOfZonenamefirst();
    }
    else
    {
        ret["zoneNameFirst"]=Json::Value();
    }
    if(getZonenamesecond())
    {
        ret["zoneNameSecond"]=getValueOfZonenamesecond();
    }
    else
    {
        ret["zoneNameSecond"]=Json::Value();
    }
    if(getZonenametitlecurrent())
    {
        ret["zoneNameTitleCurrent"]=getValueOfZonenametitlecurrent();
    }
    else
    {
        ret["zoneNameTitleCurrent"]=Json::Value();
    }
    if(getZonenametitleuncurrent())
    {
        ret["zoneNameTitleUncurrent"]=getValueOfZonenametitleuncurrent();
    }
    else
    {
        ret["zoneNameTitleUncurrent"]=Json::Value();
    }
    if(getZonenametitleex())
    {
        ret["zoneNameTitleEx"]=getValueOfZonenametitleex();
    }
    else
    {
        ret["zoneNameTitleEx"]=Json::Value();
    }
    if(getZonenamethird())
    {
        ret["zoneNameThird"]=getValueOfZonenamethird();
    }
    else
    {
        ret["zoneNameThird"]=Json::Value();
    }
    if(getLockedtext())
    {
        ret["lockedText"]=getValueOfLockedtext();
    }
    else
    {
        ret["lockedText"]=Json::Value();
    }
    if(getCanpreview())
    {
        ret["canPreview"]=getValueOfCanpreview();
    }
    else
    {
        ret["canPreview"]=Json::Value();
    }
    return ret;
}

Json::Value Zone::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getZoneid())
            {
                ret[pMasqueradingVector[0]]=getValueOfZoneid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getZoneindex())
            {
                ret[pMasqueradingVector[1]]=getValueOfZoneindex();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getType())
            {
                ret[pMasqueradingVector[2]]=getValueOfType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getZonenamefirst())
            {
                ret[pMasqueradingVector[3]]=getValueOfZonenamefirst();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getZonenamesecond())
            {
                ret[pMasqueradingVector[4]]=getValueOfZonenamesecond();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getZonenametitlecurrent())
            {
                ret[pMasqueradingVector[5]]=getValueOfZonenametitlecurrent();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getZonenametitleuncurrent())
            {
                ret[pMasqueradingVector[6]]=getValueOfZonenametitleuncurrent();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getZonenametitleex())
            {
                ret[pMasqueradingVector[7]]=getValueOfZonenametitleex();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getZonenamethird())
            {
                ret[pMasqueradingVector[8]]=getValueOfZonenamethird();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getLockedtext())
            {
                ret[pMasqueradingVector[9]]=getValueOfLockedtext();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getCanpreview())
            {
                ret[pMasqueradingVector[10]]=getValueOfCanpreview();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getZoneid())
    {
        ret["zoneId"]=getValueOfZoneid();
    }
    else
    {
        ret["zoneId"]=Json::Value();
    }
    if(getZoneindex())
    {
        ret["zoneIndex"]=getValueOfZoneindex();
    }
    else
    {
        ret["zoneIndex"]=Json::Value();
    }
    if(getType())
    {
        ret["type"]=getValueOfType();
    }
    else
    {
        ret["type"]=Json::Value();
    }
    if(getZonenamefirst())
    {
        ret["zoneNameFirst"]=getValueOfZonenamefirst();
    }
    else
    {
        ret["zoneNameFirst"]=Json::Value();
    }
    if(getZonenamesecond())
    {
        ret["zoneNameSecond"]=getValueOfZonenamesecond();
    }
    else
    {
        ret["zoneNameSecond"]=Json::Value();
    }
    if(getZonenametitlecurrent())
    {
        ret["zoneNameTitleCurrent"]=getValueOfZonenametitlecurrent();
    }
    else
    {
        ret["zoneNameTitleCurrent"]=Json::Value();
    }
    if(getZonenametitleuncurrent())
    {
        ret["zoneNameTitleUncurrent"]=getValueOfZonenametitleuncurrent();
    }
    else
    {
        ret["zoneNameTitleUncurrent"]=Json::Value();
    }
    if(getZonenametitleex())
    {
        ret["zoneNameTitleEx"]=getValueOfZonenametitleex();
    }
    else
    {
        ret["zoneNameTitleEx"]=Json::Value();
    }
    if(getZonenamethird())
    {
        ret["zoneNameThird"]=getValueOfZonenamethird();
    }
    else
    {
        ret["zoneNameThird"]=Json::Value();
    }
    if(getLockedtext())
    {
        ret["lockedText"]=getValueOfLockedtext();
    }
    else
    {
        ret["lockedText"]=Json::Value();
    }
    if(getCanpreview())
    {
        ret["canPreview"]=getValueOfCanpreview();
    }
    else
    {
        ret["canPreview"]=Json::Value();
    }
    return ret;
}

bool Zone::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("zoneId"))
    {
        if(!validJsonOfField(0, "zoneId", pJson["zoneId"], err, true))
            return false;
    }
    else
    {
        err="The zoneId column cannot be null";
        return false;
    }
    if(pJson.isMember("zoneIndex"))
    {
        if(!validJsonOfField(1, "zoneIndex", pJson["zoneIndex"], err, true))
            return false;
    }
    if(pJson.isMember("type"))
    {
        if(!validJsonOfField(2, "type", pJson["type"], err, true))
            return false;
    }
    if(pJson.isMember("zoneNameFirst"))
    {
        if(!validJsonOfField(3, "zoneNameFirst", pJson["zoneNameFirst"], err, true))
            return false;
    }
    if(pJson.isMember("zoneNameSecond"))
    {
        if(!validJsonOfField(4, "zoneNameSecond", pJson["zoneNameSecond"], err, true))
            return false;
    }
    if(pJson.isMember("zoneNameTitleCurrent"))
    {
        if(!validJsonOfField(5, "zoneNameTitleCurrent", pJson["zoneNameTitleCurrent"], err, true))
            return false;
    }
    if(pJson.isMember("zoneNameTitleUncurrent"))
    {
        if(!validJsonOfField(6, "zoneNameTitleUncurrent", pJson["zoneNameTitleUncurrent"], err, true))
            return false;
    }
    if(pJson.isMember("zoneNameTitleEx"))
    {
        if(!validJsonOfField(7, "zoneNameTitleEx", pJson["zoneNameTitleEx"], err, true))
            return false;
    }
    if(pJson.isMember("zoneNameThird"))
    {
        if(!validJsonOfField(8, "zoneNameThird", pJson["zoneNameThird"], err, true))
            return false;
    }
    if(pJson.isMember("lockedText"))
    {
        if(!validJsonOfField(9, "lockedText", pJson["lockedText"], err, true))
            return false;
    }
    if(pJson.isMember("canPreview"))
    {
        if(!validJsonOfField(10, "canPreview", pJson["canPreview"], err, true))
            return false;
    }
    return true;
}
bool Zone::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Zone::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("zoneId"))
    {
        if(!validJsonOfField(0, "zoneId", pJson["zoneId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("zoneIndex"))
    {
        if(!validJsonOfField(1, "zoneIndex", pJson["zoneIndex"], err, false))
            return false;
    }
    if(pJson.isMember("type"))
    {
        if(!validJsonOfField(2, "type", pJson["type"], err, false))
            return false;
    }
    if(pJson.isMember("zoneNameFirst"))
    {
        if(!validJsonOfField(3, "zoneNameFirst", pJson["zoneNameFirst"], err, false))
            return false;
    }
    if(pJson.isMember("zoneNameSecond"))
    {
        if(!validJsonOfField(4, "zoneNameSecond", pJson["zoneNameSecond"], err, false))
            return false;
    }
    if(pJson.isMember("zoneNameTitleCurrent"))
    {
        if(!validJsonOfField(5, "zoneNameTitleCurrent", pJson["zoneNameTitleCurrent"], err, false))
            return false;
    }
    if(pJson.isMember("zoneNameTitleUncurrent"))
    {
        if(!validJsonOfField(6, "zoneNameTitleUncurrent", pJson["zoneNameTitleUncurrent"], err, false))
            return false;
    }
    if(pJson.isMember("zoneNameTitleEx"))
    {
        if(!validJsonOfField(7, "zoneNameTitleEx", pJson["zoneNameTitleEx"], err, false))
            return false;
    }
    if(pJson.isMember("zoneNameThird"))
    {
        if(!validJsonOfField(8, "zoneNameThird", pJson["zoneNameThird"], err, false))
            return false;
    }
    if(pJson.isMember("lockedText"))
    {
        if(!validJsonOfField(9, "lockedText", pJson["lockedText"], err, false))
            return false;
    }
    if(pJson.isMember("canPreview"))
    {
        if(!validJsonOfField(10, "canPreview", pJson["canPreview"], err, false))
            return false;
    }
    return true;
}
bool Zone::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector,
                                            std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Zone::validJsonOfField(size_t index,
                            const std::string &fieldName,
                            const Json::Value &pJson,
                            std::string &err,
                            bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }

            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
