/**
 *
 *  ActivityController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "ActivityController.h"
#include <string>


void ActivityController::getOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Activity::PrimaryKeyType &&id)
{
    ActivityControllerBase::getOne(req, std::move(callback), std::move(id));
}


void ActivityController::updateOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Activity::PrimaryKeyType &&id)
{
    ActivityControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void ActivityController::deleteOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   Activity::PrimaryKeyType &&id)
{
    ActivityControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void ActivityController::get(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    ActivityControllerBase::get(req, std::move(callback));
}

void ActivityController::create(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    ActivityControllerBase::create(req, std::move(callback));
}
