/**
 *
 *  ActivityController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "ActivityControllerBase.h"

#include "Activity.h"
using namespace drogon;
using namespace drogon_model::MaaGameData::gamedata;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the activity table.
 */

class ActivityController: public drogon::HttpController<ActivityController>, public ActivityControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(ActivityController::getOne,"/api/v1/gamedata/activity/{1}",Get,Options);
    ADD_METHOD_TO(ActivityController::updateOne,"/api/v1/gamedata/activity/{1}",Put,Options);
    ADD_METHOD_TO(ActivityController::deleteOne,"/api/v1/gamedata/activity/{1}",Delete,Options);
    ADD_METHOD_TO(ActivityController::get,"/api/v1/gamedata/activity",Get,Options);
    ADD_METHOD_TO(ActivityController::create,"/api/v1/gamedata/activity",Post,Options);
    //ADD_METHOD_TO(ActivityController::update,"/api/v1/gamedata/activity",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Activity::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Activity::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Activity::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
