/**
 *
 *  CharacterController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "CharacterController.h"
#include <string>


void CharacterController::getOne(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback,
                                 Character::PrimaryKeyType &&id)
{
    CharacterControllerBase::getOne(req, std::move(callback), std::move(id));
}


void CharacterController::updateOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Character::PrimaryKeyType &&id)
{
    CharacterControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void CharacterController::deleteOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    Character::PrimaryKeyType &&id)
{
    CharacterControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void CharacterController::get(const HttpRequestPtr &req,
                              std::function<void(const HttpResponsePtr &)> &&callback)
{
    CharacterControllerBase::get(req, std::move(callback));
}

void CharacterController::create(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    CharacterControllerBase::create(req, std::move(callback));
}
