/**
 *
 *  CharactersController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "CharactersController.h"
#include <string>


void CharactersController::getOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Characters::PrimaryKeyType &&id)
{
    CharactersControllerBase::getOne(req, std::move(callback), std::move(id));
}


void CharactersController::updateOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Characters::PrimaryKeyType &&id)
{
    CharactersControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void CharactersController::deleteOne(const HttpRequestPtr &req,
                                     std::function<void(const HttpResponsePtr &)> &&callback,
                                     Characters::PrimaryKeyType &&id)
{
    CharactersControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void CharactersController::get(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    CharactersControllerBase::get(req, std::move(callback));
}

void CharactersController::create(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback)
{
    CharactersControllerBase::create(req, std::move(callback));
}
