/**
 *
 *  CharacterController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "CharacterControllerBase.h"

#include "Character.h"
using namespace drogon;
using namespace drogon_model::MaaGameData::gamedata;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the character table.
 */

class CharacterController: public drogon::HttpController<CharacterController>, public CharacterControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(CharacterController::getOne,"/api/v1/gamedata/character/{1}",Get,Options);
    ADD_METHOD_TO(CharacterController::updateOne,"/api/v1/gamedata/character/{1}",Put,Options);
    ADD_METHOD_TO(CharacterController::deleteOne,"/api/v1/gamedata/character/{1}",Delete,Options);
    ADD_METHOD_TO(CharacterController::get,"/api/v1/gamedata/character",Get,Options);
    ADD_METHOD_TO(CharacterController::create,"/api/v1/gamedata/character",Post,Options);
    //ADD_METHOD_TO(CharacterController::update,"/api/v1/gamedata/character",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Character::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Character::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Character::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
