/**
 *
 *  CharactersController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "CharactersControllerBase.h"

#include "Characters.h"
using namespace drogon;
using namespace drogon_model::MaaGameData;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the characters table.
 */

class CharactersController: public drogon::HttpController<CharactersController>, public CharactersControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(CharactersController::getOne,"/api/v1/gamedata/characters/{1}",Get,Options);
    ADD_METHOD_TO(CharactersController::updateOne,"/api/v1/gamedata/characters/{1}",Put,Options);
    ADD_METHOD_TO(CharactersController::deleteOne,"/api/v1/gamedata/characters/{1}",Delete,Options);
    ADD_METHOD_TO(CharactersController::get,"/api/v1/gamedata/characters",Get,Options);
    ADD_METHOD_TO(CharactersController::create,"/api/v1/gamedata/characters",Post,Options);
    //ADD_METHOD_TO(CharactersController::update,"/api/v1/gamedata/characters",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Characters::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Characters::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Characters::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
