/**
 *
 *  ItemController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "ItemControllerBase.h"

#include "Item.h"
using namespace drogon;
using namespace drogon_model::MaaGameData;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the item table.
 */

class ItemController: public drogon::HttpController<ItemController>, public ItemControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(ItemController::getOne,"/api/v1/gamedata/item/{1}",Get,Options);
    ADD_METHOD_TO(ItemController::updateOne,"/api/v1/gamedata/item/{1}",Put,Options);
    ADD_METHOD_TO(ItemController::deleteOne,"/api/v1/gamedata/item/{1}",Delete,Options);
    ADD_METHOD_TO(ItemController::get,"/api/v1/gamedata/item",Get,Options);
    ADD_METHOD_TO(ItemController::create,"/api/v1/gamedata/item",Post,Options);
    //ADD_METHOD_TO(ItemController::update,"/api/v1/gamedata/item",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Item::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Item::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Item::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
