/**
 *
 *  SkillController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "SkillController.h"
#include <string>


void SkillController::getOne(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback,
                             Skill::PrimaryKeyType &&id)
{
    SkillControllerBase::getOne(req, std::move(callback), std::move(id));
}


void SkillController::updateOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Skill::PrimaryKeyType &&id)
{
    SkillControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void SkillController::deleteOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Skill::PrimaryKeyType &&id)
{
    SkillControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void SkillController::get(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    SkillControllerBase::get(req, std::move(callback));
}

void SkillController::create(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    SkillControllerBase::create(req, std::move(callback));
}
