/**
 *
 *  SkillController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "SkillControllerBase.h"

#include "Skill.h"
using namespace drogon;
using namespace drogon_model::MaaGameData;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the skill table.
 */

class SkillController: public drogon::HttpController<SkillController>, public SkillControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(SkillController::getOne,"/api/v1/gamedata/skill/{1}",Get,Options);
    ADD_METHOD_TO(SkillController::updateOne,"/api/v1/gamedata/skill/{1}",Put,Options);
    ADD_METHOD_TO(SkillController::deleteOne,"/api/v1/gamedata/skill/{1}",Delete,Options);
    ADD_METHOD_TO(SkillController::get,"/api/v1/gamedata/skill",Get,Options);
    ADD_METHOD_TO(SkillController::create,"/api/v1/gamedata/skill",Post,Options);
    //ADD_METHOD_TO(SkillController::update,"/api/v1/gamedata/skill",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Skill::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Skill::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Skill::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
