/**
 *
 *  StageController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "StageController.h"
#include <string>


void StageController::getOne(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback,
                             Stage::PrimaryKeyType &&id)
{
    StageControllerBase::getOne(req, std::move(callback), std::move(id));
}


void StageController::updateOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Stage::PrimaryKeyType &&id)
{
    StageControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void StageController::deleteOne(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback,
                                Stage::PrimaryKeyType &&id)
{
    StageControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void StageController::get(const HttpRequestPtr &req,
                          std::function<void(const HttpResponsePtr &)> &&callback)
{
    StageControllerBase::get(req, std::move(callback));
}

void StageController::create(const HttpRequestPtr &req,
                             std::function<void(const HttpResponsePtr &)> &&callback)
{
    StageControllerBase::create(req, std::move(callback));
}
