/**
 *
 *  StageController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "StageControllerBase.h"

#include "Stage.h"
using namespace drogon;
using namespace drogon_model::MaaGameData;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the stage table.
 */

class StageController: public drogon::HttpController<StageController>, public StageControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(StageController::getOne,"/api/v1/gamedata/stage/{1}",Get,Options);
    ADD_METHOD_TO(StageController::updateOne,"/api/v1/gamedata/stage/{1}",Put,Options);
    ADD_METHOD_TO(StageController::deleteOne,"/api/v1/gamedata/stage/{1}",Delete,Options);
    ADD_METHOD_TO(StageController::get,"/api/v1/gamedata/stage",Get,Options);
    ADD_METHOD_TO(StageController::create,"/api/v1/gamedata/stage",Post,Options);
    //ADD_METHOD_TO(StageController::update,"/api/v1/gamedata/stage",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Stage::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Stage::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Stage::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
