/**
 *
 *  ZoneController.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "ZoneController.h"
#include <string>


void ZoneController::getOne(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback,
                            Zone::PrimaryKeyType &&id)
{
    ZoneControllerBase::getOne(req, std::move(callback), std::move(id));
}


void ZoneController::updateOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               Zone::PrimaryKeyType &&id)
{
    ZoneControllerBase::updateOne(req, std::move(callback), std::move(id));
}


void ZoneController::deleteOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               Zone::PrimaryKeyType &&id)
{
    ZoneControllerBase::deleteOne(req, std::move(callback), std::move(id));
}

void ZoneController::get(const HttpRequestPtr &req,
                         std::function<void(const HttpResponsePtr &)> &&callback)
{
    ZoneControllerBase::get(req, std::move(callback));
}

void ZoneController::create(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    ZoneControllerBase::create(req, std::move(callback));
}
