/**
 *
 *  ZoneController.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "ZoneControllerBase.h"

#include "Zone.h"
using namespace drogon;
using namespace drogon_model::MaaGameData::gamedata;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the zone table.
 */

class ZoneController: public drogon::HttpController<ZoneController>, public ZoneControllerBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(ZoneController::getOne,"/api/v1/gamedata/zone/{1}",Get,Options);
    ADD_METHOD_TO(ZoneController::updateOne,"/api/v1/gamedata/zone/{1}",Put,Options);
    ADD_METHOD_TO(ZoneController::deleteOne,"/api/v1/gamedata/zone/{1}",Delete,Options);
    ADD_METHOD_TO(ZoneController::get,"/api/v1/gamedata/zone",Get,Options);
    ADD_METHOD_TO(ZoneController::create,"/api/v1/gamedata/zone",Post,Options);
    //ADD_METHOD_TO(ZoneController::update,"/api/v1/gamedata/zone",Put,Options);
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Zone::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Zone::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Zone::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
