# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build Docker Image (Release)

on:
  push:
    # trigger on version tag push
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Metadata: Git"
      id: git-meta
      uses: 'penguin-statistics/actions/git-meta@main'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true
      
    - name: "Docker: Setup Buildx"
      uses: docker/setup-buildx-action@v2
    
    - name: "Docker: Login to GitHub Container Registry"
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: "Docker: Metadata"
      id: dockermeta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/MaaAssistantArknights/MaaGameDataServer
        tags: |
          type=semver,pattern=v${{steps.git-meta.outputs.version}}
          type=ref,event=branch
          type=ref,event=pr
        flavor: |
          latest=auto
    
    - name: "Docker: Build and Push Image"
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.dockermeta.outputs.tags }}
        labels: ${{ steps.dockermeta.outputs.labels }}
    
